navikt/familie-tilbake

- pom.xml
- src/test/kotlin/no/nav/familie/tilbake/LauncherLocal.kt
- src/test/kotlin/no/nav/familie/tilbake/LauncherLocalPostgres.kt
Fjerner cloud config i egen PR
> Bumper diverse dependencies bla. spring-boot til 2.4.3

- app-preprod.yaml
- app-prod.yaml
- src/main/kotlin/no/nav/familie/tilbake/config/OppdragMQConfig.kt
- src/main/resources/application-preprod.yaml
> Ruller tilbake MQ oppsett

- src/main/kotlin/no/nav/familie/tilbake/behandling/BehandlingService.kt
- src/main/kotlin/no/nav/familie/tilbake/oppgave/OppdaterAnsvarligSaksbehandlerTask.kt
- src/main/kotlin/no/nav/familie/tilbake/oppgave/OppgaveService.kt
- src/main/kotlin/no/nav/familie/tilbake/oppgave/OppgaveTaskService.kt
når vi oppdaterer ansvarlig saksbehandler på behandlingen, skal dette også gjøres på oppgaven.
> Oppdaterer ansvarlig saksbehandler på oppgave

- src/main/kotlin/no/nav/familie/tilbake/behandling/HentFagsystemsbehandlingService.kt
- src/main/kotlin/no/nav/familie/tilbake/behandling/task/OpprettBehandlingManueltTask.kt
- src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/batch/HentFagsystemsbehandlingTask.kt
- src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/batch/HåndterGamleKravgrunnlagBatch.kt
- src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/batch/HåndterGamleKravgrunnlagService.kt
- src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/batch/HåndterGammelKravgrunnlagTask.kt
- src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/task/FinnKravgrunnlagTask.kt
- src/test/kotlin/no/nav/familie/tilbake/kravgrunnlag/FinnKravgrunnlagTaskTest.kt
- src/test/kotlin/no/nav/familie/tilbake/kravgrunnlag/HentFagsystemsbehandlingTaskTest.kt
- src/test/kotlin/no/nav/familie/tilbake/kravgrunnlag/HåndterGamleKravgrunnlagBatchTest.kt
- src/test/kotlin/no/nav/familie/tilbake/kravgrunnlag/HåndterGammelKravgrunnlagTaskTest.kt
Nå sender jeg HentFagsystemsbehandling request i HentFagsystemsbehandlingTask og håndterer kravgrunnlag og oppretter behandling på HåndterGammelKravgrunnlagTask
> delte opp HåndterGamleKravgrunnlagBatch i 2 tasker for å fikse transaksjon problem

- src/main/kotlin/no/nav/familie/tilbake/behandling/BehandlingMapper.kt
- src/main/kotlin/no/nav/familie/tilbake/behandling/BehandlingService.kt
- src/test/kotlin/no/nav/familie/tilbake/behandling/BehandlingServiceTest.kt
- src/test/kotlin/no/nav/familie/tilbake/behandling/task/OpprettBehandlingManuellTaskTest.kt
Henter ansvarlig saksbehandlerident fra aad ved opprettelse av behandling, og bruker navident som identifikator
> Henter ansvarlig saksbehandlerident fra aad

- .github/dependabot.yml
> Legger inn igjen felles i dependabot

- src/main/kotlin/no/nav/familie/tilbake/oppgave/OppdaterAnsvarligSaksbehandlerTask.kt
- src/main/kotlin/no/nav/familie/tilbake/oppgave/OppgaveService.kt
Retter feil med oppdatering av saksbehandler på behandle underkjent vedtak oppgaver
> Finner oppgave å oppdatere uavhengig av oppgavetype

- .deploy/nais/app-dev-gcp.yaml
- .deploy/nais/app-prod-gcp.yaml
NB: Ikke merge denne PR-en før kl 14:00
> Endret cluster til familie-ba-sak

- pom.xml
- src/main/kotlin/no/nav/familie/tilbake/api/BehandlingController.kt
- src/main/kotlin/no/nav/familie/tilbake/api/BeregningController.kt
- src/main/kotlin/no/nav/familie/tilbake/api/DokumentController.kt
- src/main/kotlin/no/nav/familie/tilbake/api/FagsakController.kt
- src/main/kotlin/no/nav/familie/tilbake/api/FaktaFeilutbetalingController.kt
- src/main/kotlin/no/nav/familie/tilbake/api/ForeldelseController.kt
- src/main/kotlin/no/nav/familie/tilbake/api/JournalpostController.kt
- src/main/kotlin/no/nav/familie/tilbake/api/TotrinnController.kt
- src/main/kotlin/no/nav/familie/tilbake/api/VergeController.kt
- src/main/kotlin/no/nav/familie/tilbake/api/VilkårsvurderingController.kt
- src/main/kotlin/no/nav/familie/tilbake/api/e2e/AutotestController.kt
- src/main/kotlin/no/nav/familie/tilbake/api/forvaltning/ForvaltningController.kt
- src/main/kotlin/no/nav/familie/tilbake/behandling/FagsakRepository.kt
- src/main/kotlin/no/nav/familie/tilbake/common/ContextService.kt
- src/main/kotlin/no/nav/familie/tilbake/integration/familie/IntegrasjonerClient.kt
- src/main/kotlin/no/nav/familie/tilbake/sikkerhet/AuditLogger.kt
- src/main/kotlin/no/nav/familie/tilbake/sikkerhet/Rolletilgangssjekk.kt
- src/main/kotlin/no/nav/familie/tilbake/sikkerhet/TilgangAdvice.kt
- src/main/kotlin/no/nav/familie/tilbake/sikkerhet/Tilgangskontrollsfagsystem.kt
- src/main/resources/logback-spring.xml
- src/test/kotlin/no/nav/familie/tilbake/OppslagSpringRunnerTest.kt
- src/test/kotlin/no/nav/familie/tilbake/behandling/FagsakServiceTest.kt
- src/test/kotlin/no/nav/familie/tilbake/config/OAuth2AccessTokenTestConfig.kt
- src/test/kotlin/no/nav/familie/tilbake/sikkerhet/TilgangAdviceTest.kt
- src/test/resources/application-integrasjonstest.yaml
Legat til uthenting av fagsak for eksterFagsakId i kombinasjon med ytelsestype/fagsystem. Endret fra java-reflection til kotlin-reflection og omstruktrurert litt. Lagt til audit-logging av tilgang til personer.
> Audit logging

- src/main/resources/application-prod.yaml
Ref Slack diskusjon https://nav-it.slack.com/archives/CACJPSB1S/p1663576678710199?thread_ts=1663430841.149399&cid=CACJPSB1S
> Endrer MQ server i PROD

- src/main/kotlin/no/nav/familie/tilbake/config/Constants.kt
- src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/vedtak/handlebars/dto/HbKonfigurasjon.kt
- src/test/kotlin/no/nav/familie/tilbake/dokumentasjonsgenerator/DokumentasjonsgeneratorPeriodeVilkår.kt
Fant denne når jeg holdt på med 
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9178
> Fjerner grunnbeløpForDato som ikke brukes noe sted

- README.md
- src/main/resources/templates/nb/vedtak/periode-fakta/periode_fakta_ef.hbs
- src/main/resources/templates/nn/vedtak/periode-fakta/periode_fakta_ef.hbs
Del 2/3 i https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9178
TODO: Oppdatere confluence
> Endret tekst for endret inntekt for inntekt endret over 10%

- src/main/kotlin/no/nav/familie/tilbake/behandling/BehandlingService.kt
- src/test/kotlin/no/nav/familie/tilbake/behandling/BehandlingServiceTest.kt
Fikser veil med opprett behandling manuelt etter henlagt behandling
> Opprettbehandling manuelt

- src/main/kotlin/no/nav/familie/tilbake/behandling/batch/AutomatiskSaksbehandlingService.kt
- src/main/kotlin/no/nav/familie/tilbake/behandling/steg/StegService.kt
- src/test/kotlin/no/nav/familie/tilbake/behandling/batch/AutomatiskSaksbehandlingBatchTest.kt
- src/test/kotlin/no/nav/familie/tilbake/behandling/steg/StegServiceTest.kt
Løyser _Ikke automatisk behandle tilbakekrevinger med tema EØS_, [Tea-9671](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9671)
> Ikkje behandle EØS-behandlingar automatisk

- pom.xml
- src/main/kotlin/no/nav/familie/tilbake/api/FagsakController.kt
- src/main/kotlin/no/nav/familie/tilbake/behandling/BehandlingMapper.kt
- src/main/kotlin/no/nav/familie/tilbake/behandling/FagsakService.kt
- src/main/kotlin/no/nav/familie/tilbake/behandling/domain/Behandlingsresultat.kt
- src/test/kotlin/no/nav/familie/tilbake/behandling/BehandlingMapperTest.kt
- src/test/kotlin/no/nav/familie/tilbake/behandling/FagsakServiceTest.kt
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10404
Endepunkt for å kunne returnere vedtak fra tilbake, som kan klages på i klage. 
Avhengig av:
* https://github.com/navikt/familie-kontrakter/pull/661
> Kunne klage på vedtak fra tilbakekreving

- src/main/resources/templates/nb/vedtak/periode-særlige-grunner/periode_særlige_grunner_forstod.hbs
- src/main/resources/templates/nb/vedtak/periode_vilkår.hbs
- src/main/resources/templates/nn/vedtak/periode-særlige-grunner/periode_særlige_grunner_forstod.hbs
- src/main/resources/templates/nn/vedtak/periode_vilkår.hbs
- src/test/resources/vedtaksbrev/KS_forsett.txt
- src/test/resources/vedtaksbrev/OS_forsett.txt
- src/test/resources/vedtaksbrev/OS_fritekst_overalt.txt
- src/test/resources/vedtaksbrev/OS_ingen_tilbakekreving.txt
- src/test/resources/vedtaksbrev/OS_ingen_tilbakekreving_med_verge.txt
- vedtaksbrev hvis burde forstått, må ha forstått, forsto
- bruker mottatt feilutbetalt beløp ved god tro
- vedtaksbrev under Særlige grunner, burde eller må ha forstått
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-10545
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-10361
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-10528
> Endringer i vedtaksbrev

- .github/workflows/build.yml
- .gitignore
For å unngå fullstendig kaos i testøyemed er det greit om man "kontrollerer" deploy til test
> Ikke autodeploy til preprod

- src/main/kotlin/no/nav/familie/tilbake/behandling/steg/Foreslåvedtakssteg.kt
- src/main/kotlin/no/nav/familie/tilbake/common/ContextService.kt
- src/main/kotlin/no/nav/familie/tilbake/oppgave/LagOppgaveTask.kt
- src/main/kotlin/no/nav/familie/tilbake/oppgave/OppgaveTaskService.kt
- src/test/kotlin/no/nav/familie/tilbake/oppgave/LagOppgaveTaskTest.kt
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10519
> Godkjenne vedtak oppgaver: oppgavebeskrivelsen skal vise hvem som sendte oppgaven til beslutter

- pom.xml
- src/main/kotlin/no/nav/familie/tilbake/behandling/BehandlingMapper.kt
- src/test/kotlin/no/nav/familie/tilbake/behandling/BehandlingMapperTest.kt
Kontraktsendringen må merges i denne rekkefølgen:
* https://github.com/navikt/familie-klage/pull/223
* https://github.com/navikt/familie-tilbake/pull/962
* https://github.com/navikt/familie-ef-sak/pull/1979
* https://github.com/navikt/familie-tilbake/pull/962
> bumpet kontrakter

- .deploy/nais/app-dev-gcp.yaml
- src/main/resources/application-dev.yaml
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10604
> Tar i bruk q2

- pom.xml
- src/main/kotlin/no/nav/familie/tilbake/behandling/BehandlingMapper.kt
- src/main/kotlin/no/nav/familie/tilbake/behandling/batch/AutomatiskSaksbehandlingService.kt
- src/main/kotlin/no/nav/familie/tilbake/behandling/domain/Behandling.kt
- src/main/kotlin/no/nav/familie/tilbake/behandling/steg/StegService.kt
- src/test/kotlin/no/nav/familie/tilbake/behandling/BehandlingMapperTest.kt
- src/test/kotlin/no/nav/familie/tilbake/behandling/batch/AutomatiskSaksbehandlingBatchTest.kt
- src/test/kotlin/no/nav/familie/tilbake/behandling/steg/StegServiceTest.kt
Regelverk brukes https://github.com/navikt/familie-klage/pull/240
> Oppdater felles kontrakter og legg inn regelverk i FagsystemVedtak

- pom.xml
- src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/manuell/brevmottaker/ManuellBrevmottakerRepository.kt
- src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/manuell/brevmottaker/domene/ManuellBrevmottaker.kt
- src/main/kotlin/no/nav/familie/tilbake/historikkinnslag/TilbakekrevingHistorikkinnslagstype.kt
- src/main/resources/db/migration/V32__manuellbrevmottaker.sql
- src/test/kotlin/no/nav/familie/tilbake/DatabaseChangesTest.kt
- src/test/kotlin/no/nav/familie/tilbake/OppslagSpringRunnerTest.kt
- src/test/kotlin/no/nav/familie/tilbake/behandling/BehandlingServiceTest.kt
- src/test/kotlin/no/nav/familie/tilbake/dokumentbestilling/manuell/brevmottaker/ManuellBrevmottakerTest.kt
- src/test/kotlin/no/nav/familie/tilbake/iverksettvedtak/TilbakekrevingsvedtakBeregningServiceTest.kt
Link til [favro-oppgave](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-11849)
> databaseendringer for ManuellBrevmottaker

- .deploy/azurerator/azure-ad-app-lokal.yaml
- .deploy/nais/app-dev-gcp.yaml
- .github/kafka-manager/familie-tilbake-kafka-manager-dev.yml
- src/main/kotlin/no/nav/familie/tilbake/oppgave/OppgaveService.kt
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-11924
* https://github.com/navikt/familie-tilbake-frontend/pull/1303
> Erstatter ingressen dev.intern med intern.dev

- .github/dependabot.yml
- .github/workflows/build-and-deploy-dev.yml
- .github/workflows/build-and-deploy-prod.yml
- .github/workflows/build.yml
- .github/workflows/run-e2e.yml
* Splitter deploy til master
* Oppdaterer versjoner
Gjør det litt enklere å fortsette deploy de tilfeller noe feiler i deploy, men at bygget gikk fint
> Oppdaterer deployscripts

- src/main/kotlin/no/nav/familie/tilbake/config/FeatureToggleConfig.kt
- src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/KravgrunnlagService.kt
- src/main/kotlin/no/nav/familie/tilbake/oppgave/LagOppgaveTask.kt
- src/main/kotlin/no/nav/familie/tilbake/oppgave/OppdaterAnsvarligSaksbehandlerTask.kt
- src/main/kotlin/no/nav/familie/tilbake/oppgave/OppdaterOppgaveTask.kt
- src/main/kotlin/no/nav/familie/tilbake/oppgave/OppdaterPrioritetTask.kt
- src/main/kotlin/no/nav/familie/tilbake/oppgave/OppgavePrioritetService.kt
- src/main/kotlin/no/nav/familie/tilbake/oppgave/OppgaveService.kt
- src/main/kotlin/no/nav/familie/tilbake/oppgave/OppgaveTaskService.kt
- src/test/kotlin/no/nav/familie/tilbake/beregning/TilbakekrevingsberegningServiceTest.kt
- src/test/kotlin/no/nav/familie/tilbake/data/Testdata.kt
- src/test/kotlin/no/nav/familie/tilbake/kravgrunnlag/BehandleKravgrunnlagTaskTest.kt
- src/test/kotlin/no/nav/familie/tilbake/oppgave/LagOppgaveTaskTest.kt
- src/test/kotlin/no/nav/familie/tilbake/oppgave/OppgavePrioritetServiceTest.kt
- src/test/kotlin/no/nav/familie/tilbake/oppgave/OppgaveServiceTest.kt
Har featuretogglet dette for å teste i dev først.
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-12112
> Skal sette prioritet på oppgave utifra feilutbetalingsbeløp.

- src/main/kotlin/no/nav/familie/tilbake/common/Grunnbeløp.kt
Kan dette merges? Vil dette påvirke noen saker i prod?
> Utvider nyeste grunnbeløpsperiode for å rette tester som feiler, da den ikke fant gjeldende G etter månedskifte

- src/main/kotlin/no/nav/familie/tilbake/api/ManuellBrevmottakerController.kt
- src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/manuell/brevmottaker/ManuellBrevmottakerMapper.kt
- src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/manuell/brevmottaker/ManuellBrevmottakerService.kt
- src/test/kotlin/no/nav/familie/tilbake/dokumentbestilling/manuell/brevmottaker/ManuellBrevmottakerServiceTest.kt
Hører sammen med https://github.com/navikt/familie-tilbake-frontend/pull/1364
> Henter brevmottaker.navn fra register dersom request inneholder ident

- src/main/kotlin/no/nav/familie/tilbake/behandling/BehandlingMapper.kt
- src/main/kotlin/no/nav/familie/tilbake/behandlingskontroll/domain/Behandlingsstegstilstand.kt
- src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/manuell/brevmottaker/ManuellBrevmottakerService.kt
- src/main/kotlin/no/nav/familie/tilbake/historikkinnslag/HistorikkService.kt
- src/test/kotlin/no/nav/familie/tilbake/dokumentbestilling/manuell/brevmottaker/ManuellBrevmottakerServiceTest.kt
- src/test/kotlin/no/nav/familie/tilbake/oppgave/OppdaterAnsvarligSaksbehandlerTaskTest.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-12197
Utvider historikk innslag for brevmottaker til å inkludere info om hva som ble lagt til / endret / fjernet.
> Utvid logging av brevmottaker

- pom.xml
- src/main/kotlin/no/nav/familie/tilbake/behandling/BehandlingService.kt
- src/main/kotlin/no/nav/familie/tilbake/config/FeatureToggleConfig.kt
- src/test/kotlin/no/nav/familie/tilbake/behandling/BehandlingServiceTest.kt
- src/test/kotlin/no/nav/familie/tilbake/config/FeatureToggleMockConfig.kt
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-11474
> NAV-11474 Manuelle brevmottakere skal ikke være tilgjengelig for institusjon

- src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/manuell/brevmottaker/ManuellBrevmottakerService.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-12385
Vi ønsker å ha litt annerledes tittel på historikkinnslag når vi justerer mottakertype på eksisterende brevmottakere
> Juster historikkinnslagg tittel ved endring av mottakertype

- src/main/kotlin/no/nav/familie/tilbake/behandling/HentFagsystemsbehandlingService.kt
- src/main/kotlin/no/nav/familie/tilbake/behandling/task/OpprettBehandlingManueltTask.kt
- src/test/kotlin/no/nav/familie/tilbake/behandling/task/OpprettBehandlingManuellTaskTest.kt
Reverts navikt/familie-tilbake#1102
> Revert "Skal hente behandling fra fagsystem på nytt dersom det feilet ved forrige kjøring"

- src/main/kotlin/no/nav/familie/tilbake/behandling/HentFagsystemsbehandlingService.kt
Fortsettelse på https://github.com/navikt/familie-tilbake/pull/1105
> Skal ikke ha spesialhåndtering av feil HentFagsystemBehandlingRequest

- src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/KravgrunnlagService.kt
- src/main/kotlin/no/nav/familie/tilbake/oppgave/OppgaveTaskService.kt
OppdaterPrioritetTask feiler, men får ikke sett hvilket behandling det gjelder for å debugge. Legger til `behandlingId` som metadata til tasken.
> Legger til behandlingId som metadata på OppdaterPrioritetTask

- src/main/kotlin/no/nav/familie/tilbake/sikkerhet/AuditLogger.kt
Endringen er testet i preprod i familie-klage.
Endringen er gjort på forespørsel fra Roger Dybdal: https://nav-it.slack.com/archives/CH4NLKAR0/p1689077799460959
> Auditlogger: Logger navn på produktområde i tillegg til app da det gir mer mening for brukerne 

- src/main/kotlin/no/nav/familie/tilbake/sikkerhet/AuditLogger.kt
Ref: https://nav-it.slack.com/archives/CH4NLKAR0/p1689237228023819?thread_ts=1689077799.460959&cid=CH4NLKAR0
> Bugfix: Fjerner en header som ikke lenger skal være med etter det ble lagt til navn på PO

- src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/domain/Kravgrunnlag431.kt
Legger til baoreums som gyldig klassekode
> Legger til baoreums som gyldig klassekode

- .github/kafka-manager/familie-tilbake-kafka-manager-dev.yml
- .github/kafka-manager/familie-tilbake-kafka-manager-prod.yml
https://nav-it.slack.com/archives/CH4NLKAR0/p1690964892780659
Oppdaterer versjon av kafka-manager
> Oppdater kafka manager

- src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/domain/Kravgrunnlag431.kt
- src/main/resources/templates/nb/vedtak/vedtak_slutt.hbs
- src/main/resources/templates/nn/vedtak/vedtak_slutt.hbs
- src/test/resources/vedtaksbrev/Fritekst_Vedtaksbrev_OS_full_tilbakebetaling.txt
- src/test/resources/vedtaksbrev/KS_forsett.txt
- src/test/resources/vedtaksbrev/OS_delvis_foreldelse_uten_varsel.txt
- src/test/resources/vedtaksbrev/OS_forsett.txt
- src/test/resources/vedtaksbrev/OS_fritekst_overalt.txt
- src/test/resources/vedtaksbrev/OS_revurdering_bruker_død.txt
- src/test/resources/vedtaksbrev/OS_revurdering_bruker_død_annet_fritekst.txt
- src/test/resources/vedtaksbrev/OS_revurdering_bruker_død_nynorsk.txt
- src/test/resources/vedtaksbrev/OS_revurdering_bruker_død_nynorsk_annet_fritekst.txt
- src/test/resources/vedtaksbrev/OS_tilbakekreving_bruker_død.txt
- src/test/resources/vedtaksbrev/OS_tilbakekreving_bruker_død_nn.txt
- src/test/resources/vedtaksbrev/barnetilsyn/BT_beløp_over_6G_helt_brev_en_periode.txt
- src/test/resources/vedtaksbrev/barnetilsyn/BT_beløp_over_6G_helt_brev_flere_perioder_flere_beløp.txt
- src/test/resources/vedtaksbrev/barnetilsyn/BT_beløp_over_6G_helt_brev_flere_perioder_flere_beløp_nn.txt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-12807
Vi ønsker å rename der det står "Nav innkreving" til "Skatteetaten"
> Tekstendring (Nav innkreving -> skatteetaten)

- pom.xml
- src/main/kotlin/no/nav/familie/tilbake/api/forvaltning/ForvaltningController.kt
- src/main/kotlin/no/nav/familie/tilbake/forvaltning/ForvaltningService.kt
- src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/KravgrunnlagService.kt
- src/test/kotlin/no/nav/familie/tilbake/config/IntegrasjonerClientConfig.kt
1. Kjørt: 
- mvn versions:update-properties
- ktlint 
2: Kjørt
mvn versions:use-latest-releases -DprocessDependencyManagement=false
=> Fjernet pdfbox versjon 3.0.0 (testfeil) bruker 2.0.29 (samme som forslag i dependabot/snyk)
> Vil oppdatere noen avhengigheter

- src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/domain/Kravgrunnlag431.kt
Confluence lenke til klassekode: https://confluence.adeo.no/pages/viewpage.action?pageId=67043436&preview=%2F67043436%2F67141659%2FFunksjonell+løsningsbeskrivelse+BA+Online.doc
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-15128
Vi legger til BAUTMDMS i familie-tilbake.
> Legger til BAUTMDMS

- src/test/kotlin/no/nav/familie/tilbake/behandling/BehandlingServiceTest.kt
Burde dette heller vært løst med sortering på behandlingssteg?
> Forsøk på å fikse test som kun feiler i GHA

- .deploy/nais/app-dev-gcp.yaml
- .deploy/nais/app-prod-gcp.yaml
- .deploy/nais/unleash/unleash-apitoken-preprod.yaml
- .deploy/nais/unleash/unleash-apitoken-prod.yaml
- .github/workflows/deploy-unleash-api-token.yaml
Hvorfor er denne endringen nødvendig? ✨
Unleash Next skal taes i bruk i stedet for gamle Unleash. Trenger derfor å kunne opprette api-tokens i dev og prod for Unleash Next : https://docs.nais.io/addons/unleash-next/?h=unleash+nex#creating-a-new-api-token
Lager en workflow som trigges manuelt og som antakeligvis bare trengs og kjøres én gang.
Favro : https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-14466
> Oppretter workflow for generering av Unleash Next api-tokens

- src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/felles/header/TekstformatererHeader.kt
- src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/felles/pdf/DokprodTilHtml.kt
- src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/felles/pdf/PdfBrevService.kt
- src/test/kotlin/no/nav/familie/tilbake/dokumentbestilling/felles/header/TekstformatererHeaderTest.kt
- src/test/kotlin/no/nav/familie/tilbake/dokumentbestilling/felles/pdf/DokprodTilHtmlTest.kt
- src/test/kotlin/no/nav/familie/tilbake/dokumentbestilling/felles/pdf/PdfBrevServiceTest.kt
Klarer ikke å sende brev til Institusjoner med & i navnet. Sørger for å sanitze navnet før man sender det til pdf generering
> Generer brev til varsel for institusjon med  ampersand i navnet

- src/main/kotlin/no/nav/familie/tilbake/config/FeatureToggleConfig.kt
Trenger ikke denne controlleren da det allerede er testet at tilbake har kontakt med Unleash Next
> Fjerner featuretogglecontroller

- src/main/kotlin/no/nav/familie/tilbake/behandling/BehandlingService.kt
- src/main/kotlin/no/nav/familie/tilbake/behandlingskontroll/BehandlingskontrollService.kt
- src/main/kotlin/no/nav/familie/tilbake/config/FeatureToggleConfig.kt
- src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/DistribusjonshåndteringService.kt
- src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/felles/BrevmetadataUtil.kt
- src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/henleggelse/SendHenleggelsesbrevTask.kt
- src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/innhentdokumentasjon/InnhentDokumentasjonbrevTask.kt
- src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/varsel/SendVarselbrevTask.kt
- src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/varsel/manuelt/SendManueltVarselbrevTask.kt
- src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/vedtak/SendVedtaksbrevTask.kt
- src/main/kotlin/no/nav/familie/tilbake/oppgave/OppgavePrioritetService.kt
- src/test/kotlin/no/nav/familie/tilbake/behandling/BehandlingServiceTest.kt
- src/test/kotlin/no/nav/familie/tilbake/dokumentbestilling/DistribusjonshåndteringServiceTest.kt
- src/test/kotlin/no/nav/familie/tilbake/dokumentbestilling/henleggelse/HenleggelsesbrevServiceTest.kt
- src/test/kotlin/no/nav/familie/tilbake/dokumentbestilling/innhentdokumentasjon/InnhentDokumentasjonbrevServiceTest.kt
- src/test/kotlin/no/nav/familie/tilbake/dokumentbestilling/varsel/manuelt/ManueltVarselbrevServiceTest.kt
- src/test/kotlin/no/nav/familie/tilbake/dokumentbestilling/vedtak/VedtaksbrevServiceTest.kt
- src/test/kotlin/no/nav/familie/tilbake/oppgave/OppgavePrioritetServiceTest.kt
- src/test/resources/application-integrasjonstest.yaml
Gjerne ta en ekstra titt på endringene som er gjort i tester, inkludert sletting av test, og se at de fortsatt gir mening.
> Fjerner ubrukte toggles

- pom.xml
- src/main/kotlin/no/nav/familie/tilbake/config/ApplicationConfig.kt
- src/main/resources/application-dev.yaml
- src/main/resources/application-prod.yaml
- src/main/resources/application.yaml
- src/test/resources/application-local.yaml
Vil bruke siste versjon av prosessering. Krever implementasjon av ProsesseringInfoProvider. 
(testet i preprod - alt ok)
Erstatter: https://github.com/navikt/familie-tilbake/pull/1220 (dependabot)
> Prosessering provider

- src/main/resources/templates/nn/innhentdokumentasjon/innhent_dokumentasjon.hbs
- src/test/resources/innhentdokumentasjonbrev/innhentdokumentasjonbrev_nn.txt
- src/test/resources/innhentdokumentasjonbrev/innhentdokumentasjonbrev_nn_død_bruker.txt
- src/test/resources/innhentdokumentasjonbrev/innhentdokumentasjonbrev_nn_institusjon.txt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-9615
Anna oppdaget noe feil i nynorsk brevene som har vært der en stund - vi tar og fikser det samtidig som vi legger til brev for institusjon.
> Feilrettinger i nynorsk brev

- pom.xml
Vil oppdatere dependencies - tester i preprod før jeg merger. 
>mvn versions:update-properties
> Oppdater deps

- pom.xml
To "felles.version" i tilbake pom. 
Se linje 27: <felles.version>2.20230928165350_3e5b5e9</felles.version>
> Vil fjerne duplikat (felles.versjon)

- .github/dependabot.yml
> Dependabot groups test

- src/main/resources/templates/nn/vedtak/periode_vilkår.hbs
Favro:
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-15850
Fortsettelse av denne - bare for nynorsk:
https://github.com/navikt/familie-tilbake/pull/1225
> Legg til oppdaterte nynorsk tekster

- src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/vedtak/VedtaksbrevgeneratorService.kt
- src/test/kotlin/no/nav/familie/tilbake/dokumentbestilling/vedtak/TekstformatererVedtaksbrevTest.kt
- src/test/resources/vedtaksbrev/KS_forsett.txt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-16297
Endrer fra 6 til 3 uker for ks.
> Endre klagefrist uker for kontantstøtte

- .github/workflows/build-and-deploy-dev.yml
- .github/workflows/build-and-deploy-prod.yml
- .github/workflows/build.yml
Bytter fra ghcr.io til GAR.
Også testet Build-Deploy-Preprod https://github.com/navikt/familie-tilbake/actions/runs/6786694927
> Bytter fra ghcr til gar

- src/main/kotlin/no/nav/familie/tilbake/common/exceptionhandler/Feil.kt
- src/main/kotlin/no/nav/familie/tilbake/oppgave/OppdaterOppgaveTask.kt
- src/main/kotlin/no/nav/familie/tilbake/oppgave/OppgaveService.kt
- src/main/kotlin/no/nav/familie/tilbake/oppgave/OppgaveTaskService.kt
- src/test/kotlin/no/nav/familie/tilbake/behandling/BehandlingServiceTest.kt
- src/test/kotlin/no/nav/familie/tilbake/oppgave/OppgaveServiceTest.kt
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-16148
> Opprett ny oppgave dersom oppdaterOppgaveTask feiler fordi oppgaven er fjernet via feilregistrering

- src/main/kotlin/no/nav/familie/tilbake/api/forvaltning/ForvaltningController.kt
> Fjerner ytelsetype fra rollesjekk på identiser åpne behandlinger uten oppgave

- src/main/kotlin/no/nav/familie/tilbake/api/forvaltning/ForvaltningController.kt
> Tar i bruk integrasjonklinet og antallTreffTotalt i respons for å sjekke oppgave

- .deploy/nais/app-dev-gcp.yaml
- .deploy/nais/app-prod-gcp.yaml
- .github/workflows/build-and-deploy-dev.yml
- .github/workflows/build-and-deploy-prod.yml
- .github/workflows/build.yml
- .github/workflows/run-e2e.yml
- Dockerfile
- pom.xml
For å få litt erfaring med opentelemetry og distroless images kjører vi dette på tilbakekreving og familie-historikk en periode.
> opentelemetry, distroless image og java 21

- .github/kafka-manager/familie-tilbake-kafka-manager-dev.yml
- .github/kafka-manager/familie-tilbake-kafka-manager-prod.yml
> Bumper kafka-manager

- src/main/kotlin/no/nav/familie/tilbake/api/forvaltning/ForvaltningController.kt
- src/main/kotlin/no/nav/familie/tilbake/forvaltning/ForvaltningService.kt
Er en sak som er iverksatt men det har av ukjent årsak ikke fått denne satusen fra økonomi. må derfor manuellt sette steget til utført og fortsette som før.
> Forvaltning: sett iverksett mot oppdrag steg utført

- pom.xml
Skal oppdatere prosessering for å tilby nytt endepunkt for uthenting av status
> Oppdater prosessering

- .github/kafka-manager/familie-tilbake-kafka-manager-dev.yml
- .github/kafka-manager/familie-tilbake-kafka-manager-prod.yml
- .github/workflows/build.yml
- pom.xml
- Oppgraderer kafka manager
- Overstyrer snake.yml for å unngå critical rapportering av sikkerhetshull
> oppgrader kafka manager

- pom.xml
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-17943
> Bytter til en oppdatert fork av openHtmlToPdf-biblioteket

- src/main/kotlin/no/nav/familie/tilbake/api/forvaltning/ForvaltningController.kt
- src/main/kotlin/no/nav/familie/tilbake/datavarehus/saksstatistikk/BehandlingTilstandService.kt
>  forvalterendepunkt for å sende behandlingens tilstand til dvh på nytt.

- src/main/kotlin/no/nav/familie/tilbake/forvaltning/ForvaltningService.kt
- src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/KravgrunnlagService.kt
- src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/KravvedtakstatusService.kt
- src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/batch/HåndterGamleKravgrunnlagService.kt
- src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/domain/ØkonomiXmlMottattArkiv.kt
- src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/ØkonomiXmlMottattService.kt
- src/main/resources/db/migration/V35__nytt_felt_i_okonomi_xml_mottatt_arkiv.sql
- src/test/kotlin/no/nav/familie/tilbake/DatabaseChangesTest.kt
- src/test/kotlin/no/nav/familie/tilbake/data/Testdata.kt
- src/test/kotlin/no/nav/familie/tilbake/kravgrunnlag/HentFagsystemsbehandlingTaskTest.kt
- src/test/kotlin/no/nav/familie/tilbake/kravgrunnlag/HåndterGammelKravgrunnlagTaskTest.kt
Laget test som reproduserer feil i prod
> lagt inn nytt felt i xml_mottatt_arkiv for bedre sporbarhet.

- .github/kafka-manager/familie-tilbake-kafka-manager-dev.yml
- .github/kafka-manager/familie-tilbake-kafka-manager-prod.yml
Bumper kafka-manager. Bygg alt deployet til miljøene
> Oppdatert kafka-manager

- src/main/kotlin/no/nav/familie/tilbake/beregning/KravgrunnlagsberegningUtil.kt
- src/main/kotlin/no/nav/familie/tilbake/beregning/TilbakekrevingsberegningService.kt
- src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/varsel/VarselbrevUtil.kt
- src/main/kotlin/no/nav/familie/tilbake/foreldelse/ForeldelseMapper.kt
- src/main/kotlin/no/nav/familie/tilbake/foreldelse/ForeldelseService.kt
- src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/KravgrunnlagService.kt
- src/main/kotlin/no/nav/familie/tilbake/vilkårsvurdering/VilkårsvurderingMapper.kt
- src/main/kotlin/no/nav/familie/tilbake/vilkårsvurdering/VilkårsvurderingValidator.kt
https://favro.com/organization/98c34fb974ce445eac854de0/86f241541982404a7491d82d?card=NAV-20698
Gjør om serviceklasse til en statisk util klasse.
> Service til Util klasse

- .github/kafka-manager/familie-tilbake-kafka-manager-dev.yml
- .github/kafka-manager/familie-tilbake-kafka-manager-prod.yml
- .github/workflows/build-and-deploy-dev.yml
- .github/workflows/build-and-deploy-prod.yml
- .github/workflows/deploy-kafka-manager.yml
> Unngår å deploye kafka topics og manager ved hver deploy. Setter det til en manuell jobb.

- src/main/kotlin/no/nav/familie/tilbake/behandling/BehandlingManuellOpprettelseService.kt
- src/main/kotlin/no/nav/familie/tilbake/behandling/BehandlingMapper.kt
- src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/batch/HåndterGamleKravgrunnlagService.kt
- src/main/resources/application-e2e.yaml
- src/test/kotlin/no/nav/familie/tilbake/behandling/BehandlingMapperTest.kt
- src/test/kotlin/no/nav/familie/tilbake/data/Testdata.kt
- src/test/resources/application-integrasjonstest.yaml
> Disable unleash i tester

- src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/KravgrunnlagService.kt
- src/test/kotlin/no/nav/familie/tilbake/kravgrunnlag/BehandleKravgrunnlagTaskTest.kt
- src/test/kotlin/no/nav/familie/tilbake/kravgrunnlag/KravgrunnlagServiceTest.kt
- src/test/resources/kravgrunnlagxml/kravgrunnlag_BA_ENDR.xml
Avklart med økonomi at kravgrunnlag med nyest dato i kontrollfelt er det gjeldende.
> Bruker kontrollfelt til å bestemme hvilket kravgrunnlag som skal være aktivt

- .deploy/nais/app-dev-gcp.yaml
- .deploy/nais/app-prod-gcp.yaml
ref https://github.com/navikt/familie-tilbake/pull/1417
> Oppdaterer observability-spec med autoinstrumentation

- src/main/kotlin/no/nav/familie/tilbake/api/forvaltning/ForvaltningPreprodController.kt
- src/main/kotlin/no/nav/familie/tilbake/faktaomfeilutbetaling/FaktaFeilutbetalingMapper.kt
- src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/KravgrunnlagService.kt
- src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/domain/Kravgrunnlag431.kt
- src/main/kotlin/no/nav/familie/tilbake/oppgave/OppgavePrioritetService.kt
- src/test/kotlin/no/nav/familie/tilbake/kravgrunnlag/AutomatiskBehandlingAvKravgrunnlagUnder4RettsgebyrTest.kt
- src/test/kotlin/no/nav/familie/tilbake/oppgave/OppgavePrioritetServiceTest.kt
Dersom beløp er høyere, opprett behandle-sak oppgave.
> Sjekk at kravgrunnlag fortsatt er under 4x rettsgebyr for automatisk behandling

- src/main/kotlin/no/nav/familie/tilbake/config/Constants.kt
- src/main/kotlin/no/nav/familie/tilbake/faktaomfeilutbetaling/FaktaFeilutbetalingService.kt
- src/test/kotlin/no/nav/familie/tilbake/kravgrunnlag/AutomatiskBehandlingAvKravgrunnlagUnder4RettsgebyrTest.kt
Tar i bruk begrunnelse som blir skrevet av saksbehandler i ef-sak
> Ikke overskriv begrunnelse ved automatisk behandling

- src/main/kotlin/no/nav/familie/tilbake/behandling/BehandlingMapper.kt
- src/main/kotlin/no/nav/familie/tilbake/behandling/BehandlingService.kt
- src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/KravgrunnlagService.kt
- src/test/kotlin/no/nav/familie/tilbake/kravgrunnlag/AutomatiskBehandlingAvKravgrunnlagUnder4RettsgebyrTest.kt
- src/test/kotlin/no/nav/familie/tilbake/kravgrunnlag/BehandleKravgrunnlagTaskTest.kt
Dette for å unngå at det blir opprettet Behandle-sak / Godkjenne-sak oppgaver.
Bug er gjenskapt i preprod: https://ensligmorellerfar.ansatt.dev.nav.no/person/e4a479af-d405-4b65-967b-57626d816482/behandlinger
> Bugfix: Sett riktig behandlingstype for automatisk behandling.

- src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/batch/HåndterGamleKravgrunnlagBatch.kt
- src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/domain/ØkonomiXmlMottattIdOgYtelse.kt
- src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/ØkonomiXmlMottattRepository.kt
- src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/ØkonomiXmlMottattService.kt
- src/test/kotlin/no/nav/familie/tilbake/data/Testdata.kt
- src/test/kotlin/no/nav/familie/tilbake/kravgrunnlag/HåndterGamleKravgrunnlagBatchTest.kt
- src/test/kotlin/no/nav/familie/tilbake/kravgrunnlag/ØkonomiXmlMottattRepositoryTest.kt
- src/test/resources/application-integrasjonstest.yaml
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21086
> NAV-21086: Sprer triggertid for oppretting av tasks for kravgrunnlag på samme eksterne fagsak id

- src/main/kotlin/no/nav/familie/tilbake/behandling/batch/AutomatiskSaksbehandlingTask.kt
- src/main/kotlin/no/nav/familie/tilbake/config/Constants.kt
- src/main/resources/templates/nb/vedtak/vedtak_feilutbetaling_4x_rettsgebyr_begrunnelse.hbs
- src/test/kotlin/no/nav/familie/tilbake/kravgrunnlag/AutomatiskBehandlingAvKravgrunnlagUnder4RettsgebyrTest.kt
Vil fjerne unødvendig tekst "x" og "ganger" i under 4 rettsgebyr - tekst.
> Tekstendringer:

- pom.xml
kotlin.version: 2.0.0
token-validation-spring.version:5.0.1
verapdf.version:1.26.1
mockk.version:1.13.11
familie-tjenestespesifikasjoner.version:1.0_20240610135831_de4c522 prosessering-core.version:2.20240603145215_c56e179 com.ibm.mq.jakarta.client:9.4.0.0
pooled-jms:3.1.6
Deployet og testet en sak i preprod - alt ok
> Vil oppdatere dependencies:

- src/main/kotlin/no/nav/familie/tilbake/forvaltning/ForvaltningService.kt
Legger på `try/catch` for å fange opp og håndtere `ManglerOppgaveFeil` ved oppslag på oppgaver tilknyttet behandling for å også fange opp behandlinger som ikke har oppgave i det hele tatt og som burde hatt BehandleSak-oppgave.
> Håndterer ManglerOppgaveFeil ved sjekk om behandling er låst

- src/main/kotlin/no/nav/familie/tilbake/api/forvaltning/ForvaltningController.kt
Favro: [NAV-22019](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-22019)
Legger her til forvalter-endepunkt for å trigge kode som ferdigstiller en eventuell GodkjenneVedtak-oppgave og oppretter en ny BehandleSak-oppgave.
> Endepunkt for å ferdigstille GodkjenneVedtak-oppgave og opprette ny BehandleSak-oppgave for liste av behandlinger

- src/main/kotlin/no/nav/familie/tilbake/api/PerioderController.kt
- src/main/kotlin/no/nav/familie/tilbake/foreldelse/ForeldelseService.kt
- src/main/kotlin/no/nav/familie/tilbake/foreldelse/domain/Foreldelsesperiode.kt
- src/test/kotlin/no/nav/familie/tilbake/foreldelse/ForeldelseServiceTest.kt
Sjekker om foreldelsesperioder er like, for å sjekke om brev kan sammenslås.
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-20733)
> Likhet foreldelse perioder

- src/main/kotlin/no/nav/familie/tilbake/behandling/BehandlingService.kt
- src/main/kotlin/no/nav/familie/tilbake/sikkerhet/TilgangService.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23064
Endrer måten forvalter rollen sjekkes på når man skal sette flagget kanSetteTilbakeTilFakta i behandlingen.
> Endre måten forvalter rollen sjekkes på

- pom.xml
- src/test/kotlin/no/nav/familie/tilbake/integration/økonomi/OppdragClientTest.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23887
> Oppdaterer til spring 3.4.1

- src/main/kotlin/no/nav/familie/tilbake/oppgave/OppgaveTaskService.kt
Legger til behandlingId i properties for oppdaterEnhetOppgaveTask slik at det er lettere å finne i familie-prosessering når det skjer feil
> Legg til behandlingId i properties for oppdaterEnhetOppgaveTask 

- src/main/kotlin/no/nav/familie/tilbake/behandling/batch/AutomatiskSaksbehandlingTask.kt
- src/main/kotlin/no/nav/familie/tilbake/config/Constants.kt
- src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/KravgrunnlagService.kt
- src/test/kotlin/no/nav/familie/tilbake/config/ConstantsTest.kt
- src/test/kotlin/no/nav/familie/tilbake/data/Testdata.kt
- src/test/kotlin/no/nav/familie/tilbake/kravgrunnlag/AutomatiskBehandlingAvKravgrunnlagUnder4RettsgebyrTest.kt
- src/test/kotlin/no/nav/familie/tilbake/kravgrunnlag/KravgrunnlagServiceTest.kt
Vil vurdere om kravgrunnlag/behandling er under fire rettsgebyr for riktig år. Skal ikke bruke rettsgebyr for "now()" hvis siste feilutbetaling er i et annet år.
> Vil vurdere om kravgrunnlag/behandling er under fire rettsgebyr... 

- src/test/kotlin/no/nav/familie/tilbake/config/KafkaLokalConfig.kt
Manglet riktige variabler etter renaming av kafka-variabler
> Endrer til å bruke variabler fra kafkaconfig

- .deploy/nais/app-prod-gcp-tilbake.yaml
La den i feil fil i forrige PR for prod.
> Legger til familie-oppdrag i outbound i riktig nais.yaml fil for prod

- src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/felles/pdf/DokprodTilHtml.kt
- src/main/resources/formats/pdf/style.css
- src/main/resources/templates/nb/vedtak/vedtak_slutt.hbs
- src/main/resources/templates/nn/vedtak/vedtak_slutt.hbs
- src/test/resources/vedtaksbrev/BA_ikke_tilbakekreves_pga_lavt_beløp_død_bruker.txt
- src/test/resources/vedtaksbrev/BA_ikke_tilbakekreves_pga_lavt_beløp_død_bruker_nynorsk.txt
- src/test/resources/vedtaksbrev/Fritekst_Vedtaksbrev_KS_ingen_tilbakebetaling.txt
- src/test/resources/vedtaksbrev/Fritekst_Vedtaksbrev_OS_full_tilbakebetaling.txt
- src/test/resources/vedtaksbrev/KS_forsett.txt
- src/test/resources/vedtaksbrev/OS_delvis_foreldelse_uten_varsel.txt
- src/test/resources/vedtaksbrev/OS_forsett.txt
- src/test/resources/vedtaksbrev/OS_forsett_bruker_har_ikke_uttalt_seg.txt
- src/test/resources/vedtaksbrev/OS_fritekst_overalt.txt
- src/test/resources/vedtaksbrev/OS_ikke_tilbakekreves_med_korrigert_beløp.txt
- src/test/resources/vedtaksbrev/OS_ikke_tilbakekreves_pga_lavt_beløp.txt
- src/test/resources/vedtaksbrev/OS_ingen_tilbakekreving.txt
- src/test/resources/vedtaksbrev/OS_ingen_tilbakekreving_bruker_død.txt
- src/test/resources/vedtaksbrev/OS_ingen_tilbakekreving_bruker_død_nn.txt
- src/test/resources/vedtaksbrev/OS_ingen_tilbakekreving_med_verge.txt
- src/test/resources/vedtaksbrev/OS_revurdering_bruker_død.txt
- src/test/resources/vedtaksbrev/OS_revurdering_bruker_død_annet_fritekst.txt
- src/test/resources/vedtaksbrev/OS_revurdering_bruker_død_nynorsk.txt
- src/test/resources/vedtaksbrev/OS_revurdering_bruker_død_nynorsk_annet_fritekst.txt
- src/test/resources/vedtaksbrev/OS_tilbakekreving_bruker_død.txt
- src/test/resources/vedtaksbrev/OS_tilbakekreving_bruker_død_nn.txt
- src/test/resources/vedtaksbrev/barnetilsyn/BT_beløp_over_6G_helt_brev_en_periode.txt
- src/test/resources/vedtaksbrev/barnetilsyn/BT_beløp_over_6G_helt_brev_flere_perioder_flere_beløp.txt
- src/test/resources/vedtaksbrev/barnetilsyn/BT_beløp_over_6G_helt_brev_flere_perioder_flere_beløp_nn.txt
https://trello.com/c/CX6vxYkw/14-brev-endre-plassering-av-signaturer-i-brev-i-tr%C3%A5d-med-ny-brevstandard
> Byttet rekkefølge på beslutter og saksbehandler i vedtaks-signatur

- pdf/src/main/kotlin/no/nav/tilbakekreving/pdf/handlebars/FellesTekstformaterer.kt
I praksis vil ikke problemer med denne koden intreffe siden vi ikke har nok trafikk til at cachen fylles i parallell. I testene gjør det at det feiler med jevne mellomrom
> Forbedre trådsikkerhet i pdf caching
