navikt/familie-tilbake

.github/workflows/build-and-deploy-preprod.yml, src/main/resources/db/migration/V2__altered_fagsak.sql, src/test/kotlin/no/nav/familie/tilbake/DatabaseChangesTest.kt
**Stoppet å deployere i prepod for draft pull request
=> TEA-3532 Tillatt å opprette flere behandlinger på samme eksternFagsakId med forskjellige ytelsestype. 

src/main/kotlin/no/nav/familie/tilbake/service/dokumentbestilling/vedtak/AvsnittUtil.kt, src/main/kotlin/no/nav/familie/tilbake/service/dokumentbestilling/vedtak/VedtaksbrevService.kt, src/main/kotlin/no/nav/familie/tilbake/service/dokumentbestilling/vedtak/handlebars/dto/HbVarsel.kt, src/main/resources/templates/nb/vedtak/vedtak_felles.hbs, src/main/resources/templates/nn/vedtak/vedtak_felles.hbs, src/test/kotlin/no/nav/familie/tilbake/service/dokumentbestilling/vedtak/AvsnittUtilTest.kt, src/test/kotlin/no/nav/familie/tilbake/service/dokumentbestilling/vedtak/VedtaksbrevServiceTest.kt, src/test/resources/vedtaksbrev/OS_ikke_tilbakekreves_med_korrigert_beløp.txt
Varsel er ikke lenger påkrevd
kroner kroner er fjernet
Avsnitt og underavsnitt tillater fdritekst når de skal det.
=> Feilrettinger på vedtaksbrev

src/main/kotlin/no/nav/familie/tilbake/behandling/VarselService.kt, src/main/resources/templates/nn/varsel/korrigert_varsel.hbs
Feil dato skyldtes at varsler ikke ble satt inaktive når nye ble opprettet.
=> Fikset datorformat i brev og feil dato på varsel

src/main/kotlin/no/nav/familie/tilbake/micrometer/MålerService.kt
Økt ventetidenn fra oppstart til henting av data, for å være sikker på at systemet er oppe og kjører før spørringene kjøres.
=> Økt initialDelay på i MålerService

pom.xml
Setter test scope på token-validation-spring-test for å unngå å få med `mock-oauth2-server-0.3.3.jar!/logback.xml `med i classpath for prod.
=> setter test scope på token-validation-spring-test

.github/workflows/build-and-deploy-dev.yml, .github/workflows/run-e2e.yml
Vi har rullet ut en ny org-wide secret som kan brukes for å sjekke ut andre repos og hente pakker i en workflow. Denne PRen bytter derfor ut installation tokens med den nye secreten.
=> Bruk READER_TOKEN i stedet for GitHub App

src/main/resources/logback-spring.xml
LinkerD lukker ofte forbindelsene for tidlig når vi gjør en shutdown, noe som fører til at noen logevents til securelogs kanforsvinne. Går over til å bruke default mekanisme for securelogs.
=> securelog via fil

src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/felles/pdf/PdfBrevService.kt
I denne tråden så opplyses det om at eksternReferanseId kan støtte opptil 200tegn. Så det er godt innanfor. :)
https://nav-it.slack.com/archives/C6W9E5GPJ/p1646131673515049
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/86f241541982404a7491d82d?card=Tea-10223
=> TEA-10223 Inkluderer callId i eksternReferanseId, så same brev kan sendes flere gonger på behandling

src/main/kotlin/no/nav/familie/tilbake/behandling/BehandlingService.kt, src/main/kotlin/no/nav/familie/tilbake/integration/familie/IntegrasjonerClient.kt, src/main/kotlin/no/nav/familie/tilbake/oppgave/OppdaterEnhetOppgaveTask.kt, src/main/kotlin/no/nav/familie/tilbake/oppgave/OppgaveService.kt, src/test/kotlin/no/nav/familie/tilbake/kravgrunnlag/HentFagsystemsbehandlingTaskTest.kt
For kontantstøtte og barnetrygd så nullstilles mappen ved flytting av oppgaven, siden mappeId tilhører enheten. Ingen endring for Enslig forsørger. De skal ha gått over til å bruke felles mapper.
Flytting skjer med 2 kall mot oppgave, hvor den ene oppdaterer data som beskrivelse, saksbehandler, mens selve enhetbytte skjer med å kalle endepunkt som ble tatt i bruk i ba-sak, som støtter å flytte med og uten mappe.
=> Støtte for å endre enhet når det er mappe registrert på oppgaven

pom.xml, src/main/kotlin/no/nav/familie/tilbake/behandling/BehandlingMapper.kt, src/test/kotlin/no/nav/familie/tilbake/behandling/BehandlingMapperTest.kt
En start på [denne oppgaven](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10592)
Tar i bruk `VedtakType` fra kontrakter, som kan være `SANKSJON_1_MND`
Har også endret kontrakter i `ef-sak` og `familie-klage`:
* https://github.com/navikt/familie-ef-sak/pull/1972
* https://github.com/navikt/familie-klage/pull/218
=> fagsystemVedtak skal kunne vite om vedtakstypen er en sanksjon

src/main/kotlin/no/nav/familie/tilbake/oppgave/OppgaveService.kt
Logger ekstern fagsakId når oppgave ikke finnes for behandling.
Dette gjør at utviklere slipper å søke opp i databasen for å finne fagsaken til behandlingen.
Ser forsåvidt at fagsakId'en logges ut som saksnummer sendt til dvh, men det er veldig vanskelig å finne frem til hvis man ikke vet at det er samme id.
=> Chore: Logg ekstern fagsakId når oppgave ikke finnes

src/main/kotlin/no/nav/familie/tilbake/oppgave/OppdaterAnsvarligSaksbehandlerTask.kt, src/test/kotlin/no/nav/familie/tilbake/oppgave/OppdaterAnsvarligSaksbehandlerTaskTest.kt
En liten forbedring?
Dersom noen raser gjennom saksbehandling kan vi få flere oppgaver av typer "oppdater ansvarlig saksbehandler" som plukkes samtidig. Da kan en av disse få en 409 - (oppgaven er i feil versjon). 
Dette pleier stort sett ordne seg når man re-kjører og henter oppgave på nytt, men i noen tilfeller rekker saksbehandler å ferdigstille behandling/oppgave før vi får kjørt på nytt. Da feiler tasken med "oppgave finnes ikke". 
Med denne endringen vil vi ikke forsøke oppdatere/patche oppgave dersom saksbehandler og prioritet er uendret.
=> Liten forbedring av oppgavepatching

src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/innhentdokumentasjon/handlebars/dto/InnhentDokumentasjonsbrevsdokument.kt, src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/varsel/handlebars/dto/Varselbrevsdokument.kt, src/main/resources/templates/nb/innhentdokumentasjon/innhent_dokumentasjon.hbs, src/main/resources/templates/nb/varsel/varsel_slutt.hbs, src/main/resources/templates/nn/innhentdokumentasjon/innhent_dokumentasjon.hbs, src/main/resources/templates/nn/varsel/varsel_slutt.hbs, src/test/kotlin/no/nav/familie/tilbake/dokumentbestilling/varsel/TekstformatererVarselbrevTest.kt, src/test/kotlin/no/nav/familie/tilbake/dokumentbestilling/varsel/VarselbrevServiceTest.kt, src/test/resources/varselbrev/BA_en_periode.txt, src/test/resources/varselbrev/KS_en_periode.txt
Favro: [NAV-12218](https://favro.com/organization/98c34fb974ce445eac854de0/077068028bffba85055cca2d?card=NAV-12218)
Legger til henvisning til kontantstøtteloven/-lova i varselbrev 
Resultat for hhv skolepenger, barnetrygd og kontantstøtte:
[test-skolepenger.pdf](https://github.com/navikt/familie-tilbake/files/11231031/test-skolepenger.pdf)
[test-barnetrygd.pdf](https://github.com/navikt/familie-tilbake/files/11231032/test-barnetrygd.pdf)
[test-kontantstøtte.pdf](https://github.com/navikt/familie-tilbake/files/11231033/test-kontantstotte.pdf)
=> Vis til kontantstøtteloven i varselbrev for KONTANTSTØTTE

pom.xml, src/main/kotlin/no/nav/familie/tilbake/api/ManuellBrevmottakerController.kt, src/main/kotlin/no/nav/familie/tilbake/api/dto/BehandlingDto.kt, src/main/kotlin/no/nav/familie/tilbake/api/dto/BehandlingsstegDto.kt, src/main/kotlin/no/nav/familie/tilbake/behandling/BehandlingMapper.kt, src/main/kotlin/no/nav/familie/tilbake/behandling/BehandlingService.kt, src/main/kotlin/no/nav/familie/tilbake/behandling/VergeService.kt, src/main/kotlin/no/nav/familie/tilbake/behandling/steg/Brevmottakersteg.kt, src/main/kotlin/no/nav/familie/tilbake/behandling/steg/FaktaFeilutbetalingssteg.kt, src/main/kotlin/no/nav/familie/tilbake/behandling/steg/Fattevedtakssteg.kt, src/main/kotlin/no/nav/familie/tilbake/behandling/steg/Foreldelsessteg.kt, src/main/kotlin/no/nav/familie/tilbake/behandling/steg/Foreslåvedtakssteg.kt, src/main/kotlin/no/nav/familie/tilbake/behandling/steg/Grunnlagssteg.kt, src/main/kotlin/no/nav/familie/tilbake/behandling/steg/StegService.kt, src/main/kotlin/no/nav/familie/tilbake/behandling/steg/Varselssteg.kt, src/main/kotlin/no/nav/familie/tilbake/behandling/steg/Vergessteg.kt, src/main/kotlin/no/nav/familie/tilbake/behandling/steg/Vilkårsvurderingssteg.kt, src/main/kotlin/no/nav/familie/tilbake/behandlingskontroll/BehandlingskontrollService.kt, src/main/kotlin/no/nav/familie/tilbake/behandlingskontroll/domain/Behandlingsstegstilstand.kt, src/main/kotlin/no/nav/familie/tilbake/config/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/felles/task/PubliserJournalpostTask.kt, src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/manuell/brevmottaker/ManuellBrevmottakerService.kt, src/main/kotlin/no/nav/familie/tilbake/iverksettvedtak/task/AvsluttBehandlingTask.kt, src/main/kotlin/no/nav/familie/tilbake/iverksettvedtak/task/SendØkonomiTilbakekrevingsvedtakTask.kt, src/test/kotlin/no/nav/familie/tilbake/dokumentbestilling/felles/task/PubliserJournalpostTaskDistribuererTilRettAdresseTest.kt, src/test/kotlin/no/nav/familie/tilbake/dokumentbestilling/manuell/brevmottaker/ManuellBrevmottakerServiceTest.kt
Fikser også et par av funksjonene i ManuellBrevmottakerController som ikke var tatt i bruk og testet enda, samt legger til to nye for aktivering/deaktivering av det nye steget.
Hører sammen med denne frontend-PR'en: https://github.com/navikt/familie-tilbake-frontend/pull/1348
=> Legger til nytt behandlingssteg for manuell registrering av brevmottakere

src/main/kotlin/no/nav/familie/tilbake/behandling/HentFagsystemsbehandlingService.kt
Skal slettes etter at den er kjørt i prod.
Stopper lesing av kafka-melding som er introdusert av feil i #1102 og revertet i #1104
=> Skal ikke prøve å lagre ned respons fra kafka for id pga. feil i PR 1102

src/main/kotlin/no/nav/familie/tilbake/behandling/HentFagsystemsbehandlingService.kt
Disse reponsene vil feile ved lagring/håndtering. Gjorde et søk i kibana på eksternId og fant overstående requestIder. Følger opp eksternId 67787 neste uke.
=> Skal midlertidig ikke lagre responser for eksternId 67787

src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/DistribusjonshåndteringService.kt, src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/felles/BrevmetadataUtil.kt, src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/felles/Brevmottager.kt, src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/felles/BrevmottagerUtil.kt, src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/felles/pdf/JournalføringService.kt, src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/henleggelse/HenleggelsesbrevService.kt, src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/manuell/brevmottaker/domene/ManuellBrevmottaker.kt, src/test/kotlin/no/nav/familie/tilbake/dokumentbestilling/DistribusjonshåndteringServiceTest.kt, src/test/kotlin/no/nav/familie/tilbake/dokumentbestilling/henleggelse/HenleggelsesbrevServiceTest.kt
La også til en enhetstest som verifiserer løsningen. Oppdaget og fikset da samtidig en unødvendig henting av data på nytt i HenleggelsesbrevService når metadata er forhåndsgenerert av BrevmetadataUtil
=> Fix: eksternReferanseId til dokarkiv ble den samme ved 2 manuelle mottakere

src/main/kotlin/no/nav/familie/tilbake/api/forvaltning/ForvaltningController.kt, src/main/kotlin/no/nav/familie/tilbake/forvaltning/ForvaltningService.kt, src/test/kotlin/no/nav/familie/tilbake/forvaltning/ForvaltningServiceTest.kt
**Hvorfor?**
Etter https://github.com/navikt/familie-tilbake/pull/1110 trenger man ikke lengre å bruke forvaltningsrutinen for å hente fagsystembehandling på nytt. Det skal nå være nok å rekjøre tasken.
=> Skal ikke lengre bruke forvaltningsrutine for å hente fagsystemsbehandling på nytt

src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/felles/BrevmetadataUtil.kt, src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/vedtak/VedtaksbrevgeneratorService.kt
Med funksjonsbryteren for manuelle brevmottakere påskrudd, ble beslutters signatur vist to ganger, da genereringen av brevmetadata for forhåndsvisning manglet vedtaksbrevgrunnlaget.
Før:
Etter:
=> Fikser feil saksbehandlersignatur ved forhåndsvisning av vedtaksbrev

src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/felles/task/LagreBrevsporingTask.kt, src/test/kotlin/no/nav/familie/tilbake/dokumentbestilling/felles/task/LagreBrevsporingTaskTest.kt
… selv om behandlingen har to brevmottakere.
Det var en avsluttBehandling-task som feilet da behandlingen hadde en manuelt registrert tilleggsmottaker.
Logikken som skal hindre at det opprettes to avsluttBehandling-tasker fungerte bare for tilleggsmottaker av type VERGE, men er nå oppdatert til å gjelde for MANUELL_TILLEGGSMOTTAKER i tillegg.
=> Sørger for at det kun opprettes en avsluttBehandling-task fra LagrebrevsporingTask sin onCompletion

.github/workflows/build.yml
Se dokumentasjon av konfigurasjonen her: https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
> **Example: Only cancel in-progress jobs or runs for the current workflow**
> If you have multiple workflows in the same repository, concurrency group names must be unique across workflows to avoid canceling in-progress jobs or runs from other workflows. Otherwise, any previously in-progress or pending job will be canceled, regardless of the workflow.
> 
> To only cancel in-progress runs of the same workflow, you can use the github.workflow property to build the concurrency group:
> ```
> concurrency:
>   group: ${{ github.workflow }}-${{ github.ref }}
>   cancel-in-progress: true
> ```
=> Avbryt build-workflow dersom ny kjøring av samme workflow startes på samme branch

src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/domain/Kravgrunnlag431.kt
Fjerner `KONT` fra `Klassekode`-enum da det viste seg å være riktig å bruke `KS` som klassekode for kontantstøtte.
=> Fjerner KONT fra Klassekode enum

src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/batch/HåndterGamleKravgrunnlagService.kt
**Hvorfor**
Var en del warnings på dette i prod i dag, så det kan være greit å se hvem som har ansvar for å følge opp uten å måtte søke opp callId for hver enkelt.
=> Logger stønadstype ved warning på avvik mellom hentet kravgrunnlag og mottatt kravgrunnlag

src/main/kotlin/no/nav/familie/tilbake/behandling/ValiderBrevmottakerService.kt, src/main/kotlin/no/nav/familie/tilbake/behandling/steg/StegService.kt, src/main/kotlin/no/nav/familie/tilbake/config/PdlConfig.kt, src/main/kotlin/no/nav/familie/tilbake/integration/pdl/PdlClient.kt, src/main/kotlin/no/nav/familie/tilbake/integration/pdl/internal/PdlAdressebeskyttelsePerson.kt, src/main/kotlin/no/nav/familie/tilbake/integration/pdl/internal/PdlBolkResponse.kt, src/main/kotlin/no/nav/familie/tilbake/integration/pdl/internal/PdlPersonRequest.kt, src/main/kotlin/no/nav/familie/tilbake/integration/pdl/internal/PdlPersonRequestVariables.kt, src/main/kotlin/no/nav/familie/tilbake/integration/pdl/internal/PdlUtil.kt, src/main/kotlin/no/nav/familie/tilbake/person/PersonService.kt, src/main/resources/pdl/hent-adressebeskyttelse-bolk.graphql, src/test/kotlin/no/nav/familie/tilbake/behandling/ValiderBrevmottakerServiceTest.kt, src/test/kotlin/no/nav/familie/tilbake/config/PdlClientConfig.kt
* Nytt PDL kall i PDLClient for å sjekke STRENGT_FORTROLIG / STRENGT_FORTROLIG_UTLAND adressebeskyttelse
* Lagt til validering i siste steg (FORESLÅ_VEDTAK) for at behandling med "strengt fortrolig person" (adressebeskyttelse: STRENGT_FORTROLIG eller STRENGT_FORTROLIG_UTLAND) ikke tillates å ha manuelle brevmottakere.
* ktlint
=> NAV-13827 - validering at manuelle brevmottakere ikke er tillatt for fortrolig bruker

src/main/kotlin/no/nav/familie/tilbake/behandling/ValiderBrevmottakerService.kt, src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/manuell/brevmottaker/ManuellBrevmottakerService.kt, src/test/kotlin/no/nav/familie/tilbake/behandling/ValiderBrevmottakerServiceTest.kt, src/test/kotlin/no/nav/familie/tilbake/dokumentbestilling/manuell/brevmottaker/ManuellBrevmottakerServiceTest.kt
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-13885
Lagt til validering for at det ikke er tillatt med manuelle brevmottakere når behandlingen inneholder fortrolig person (person med adressebeskyttelse STRENGT_FORTROLIG / STRENGT_FORTROLIG_UTLAND) i “leggTilBrevmottaker” og i “opprettBrevmottakerSteg”.
Visning av validerings-feilmelding i frontend er allerede merget i familie-tilbake-frontend i egne PR: 
https://github.com/navikt/familie-tilbake-frontend/pull/1460 og
https://github.com/navikt/familie-tilbake-frontend/pull/1464
=> NAV-13885 - Lagt til utvidet validering for at det ikke er tillatt med manuelle brevmottakere når behandlingen inneholder fortrolig person

.deploy/nais/app-dev-gcp.yaml, .deploy/nais/app-prod-gcp.yaml
Anbefaling fra NAIS om at CPU throttle fjernes fra pod, men beholdes for requests: https://nav-it.slack.com/archives/C01DE3M9YBV/p1680172494569329
Artikkelen som det refereres til i meldingen fra NAIS beskriver hvorfor:
https://home.robusta.dev/blog/stop-using-cpu-limits
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-12306)
=> Fjerner CPU-limit

src/main/kotlin/no/nav/familie/tilbake/common/exceptionhandler/Feil.kt, src/main/kotlin/no/nav/familie/tilbake/integration/økonomi/OppdragClient.kt, src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/batch/HåndterGamleKravgrunnlagService.kt, src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/batch/HåndterGammelKravgrunnlagTask.kt, src/test/kotlin/no/nav/familie/tilbake/kravgrunnlag/HåndterGammelKravgrunnlagTaskTest.kt
… som workaround for UnexpectedRollbackException etter det ble lagt til logikk for automatisk håndtering av gamle kravgrunnlag ikke funnet hos økonomi. Hører nok mer naturlig hjemme der uansett..
=> Flytter try-catch blokka lagt til i HåndterGammelKravgrunnlagTask inn i håndter-funksjonen

pom.xml
Swagger virker ikke etter oppgradering til Spring 3. Det må brukes andre avhengigheter av springdoc for å være kompatibel med Spring 3.
Testet i preprod og ser ut til å virke: https://familie-tilbake.intern.dev.nav.no/swagger-ui/index.html
=> Swagger spring 3

src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/batch/HåndterGamleKravgrunnlagService.kt
Trenger ikke kreve at statusmelding og kravgrunnlag skal ha lik referanse i 'harKravstatusAvsluttet', siden det er strengere enn da kravgrunnlaget ble arkivert på bakgrunn av den samme statusmeldingen til å begynne med.
=> Mindre streng "harKravstatusAvsluttet"-sjekk i HåndterGamleKravgrunnlagService  

src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/felles/pdf/PdfBrevService.kt
Har et par varselbrev som feiler med pdf generering
javax.xml.transform.TransformerException: org.xml.sax.SAXParseException; lineNumber: 239; columnNumber: 28; The entity name must immediately follow the '&' in the entity reference.
=> Litt mer logging når det feiler ved generering av brev

src/main/resources/templates/nb/vedtak/periode_vilkår.hbs, src/test/resources/vedtaksbrev/OS_fritekst_overalt.txt
Favro:
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-15850
Vi ønsker å justere litt av teksten som dukker opp i vedtaksbrevet når kombinasjonen er forsett + mangelfullopplsning og forsett + feil opplysning.
Forsett + mangelopplysning
Forsett + feilopplysning
=> Vi endrer på teksten som dukker opp i vedtaksbrevet ved forsett + mangellfull opplysning og forsett + feil opplysning

src/main/kotlin/no/nav/familie/tilbake/config/FeatureToggleConfig.kt
Hvorfor ?
DefaultUnleashService skal ikke bønnes opp i FeatureToggleConfig, siden dette gjøres nå i felles. Denne må derfor fjernes.
Testet ok i dev.
=> Rettelse i Unleash config

pom.xml, src/test/resources/kotest.properties
Byggene etter https://github.com/navikt/familie-tilbake/commit/fc95e191512aa6302d888b6c9f95793c95961102 tar veldig lang tid
https://kotlinlang.slack.com/archives/CT0G9SD7Z/p1694159552294569?thread_ts=1694104017.743329&cid=CT0G9SD7Z
```
See this link: https://kotest.io/docs/intellij/intellij-properties.html
Try adding a separate runtime properties file at /resources/kotest.properties. The resources dir should be a sibling of your kotlin dir.
Content:
kotest.framework.classpath.scanning.autoscan.disable=true
kotest.framework.classpath.scanning.config.disable=true
kotest.framework.config.fqn=com.example.ProjectConfig
```
https://kotest.io/docs/intellij/intellij-properties.html#common-use-case
=> kotest 5.7.x har autoscan av classpath, som skaper trøbbel

src/test/kotlin/no/nav/familie/tilbake/LauncherLocal.kt, src/test/kotlin/no/nav/familie/tilbake/LauncherLocalPostgres.kt, src/test/kotlin/no/nav/familie/tilbake/config/TestLauncherConfig.kt, src/test/resources/hentMiljøvariabler-lokal.sh, src/test/resources/hentMiljøvariabler-preprod.sh
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-16843
På samme måte som i BA-sak så ønsker vi å automatisk hente og sette clientId/clientSecret når vi kjører tjenesten lokalt.
Merk at kommandoene for lokal-secrets er litt annerledes, fordi der henter vi secrets fra en kubernetes secrets og ikke fra pod variabel som når vi går mot preprod.
=> Hent og sett client id og secret automatisk

src/main/kotlin/no/nav/familie/tilbake/oppgave/OppgaveService.kt
Fjerner behandlingstype i finnOppgave for å kunne finne oppgaver som saksbehandler har flyttet i Gosys
Samme som: https://github.com/navikt/familie-tilbake/pull/1246
Oppgaver blir ikke ferdigstilt hvis saksbehandler har byttet behandlingstype i gosys, fordi den ikke finner oppgaver på Tilbakekreving når den er flyttet til EØS.
=> Fjerner behandlingstype i finnOppgave for å kunne finne oppgaver som saksbehandler har flyttet i Gosys

src/main/kotlin/no/nav/familie/tilbake/oppgave/OppdaterOppgaveTask.kt
Kan sikkert justere ned log level til warn, sånn at det ikke skal komme alarm hver gang oppgave gjenopprettes, nå som forventet oppførsel er verifisert i prod
=> Justerer ned log level til warn ved gjenoppretting av oppgave i OppdaterOppgaveTask

src/main/kotlin/no/nav/familie/tilbake/api/forvaltning/ForvaltningController.kt, src/main/kotlin/no/nav/familie/tilbake/oppgave/FinnGammelBehandlingUtenOppgaveTask.kt, src/main/kotlin/no/nav/familie/tilbake/oppgave/OppgaveTaskService.kt
Flytter kode i forvaltning for å finne behandlinger uten oppgave til en task, slik at man kjører med token som har lov til å lese oppgave. Siden at token man får når man logger inn i swagger ikke har tilgang til oppgaven og lager støy eksternt hos #team-intern-samhand. Ved å flytte det til en task, så vil tasken kjørt med client_credentials.
=> Fikser at FinnÅpneBehandlingerUtenOppgave kjøres med token som har lov til å lese oppgave.

src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/ØkonomiXmlMottattService.kt, src/test/kotlin/no/nav/familie/tilbake/kravgrunnlag/BehandleStatusmeldingTaskTest.kt
Får inn mange feilmelding på behandleStatusmelding fordi vi ikke finner mottat Kravgrunnlag i okonomi_xml_mottatt. Dette skjer fordi vi typisk har plukket to kravgrunnlag i en task og arkivert begge siden den første har kravstatusskode = avsluttet. 
I disse tilfellene går vi utifra at det er riktig at kravgrunnlagene skal være arkivert og at vi derfor ikke vil kaste en feil. Går derfor videre med emptyList()
=> sjekk om mottatt kravgrunnlag allerede er blitt arkivert dersom det ikke ligger i db

src/test/kotlin/no/nav/familie/tilbake/dokumentbestilling/vedtak/VedtaksbrevServiceTest.kt
Favro: [NAV-18186](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-18186)
Sørger for at testen (`lagreUtkastAvFriteksterFraSaksbehandler skal lagre selv når påkrevet fritekst mangler for oppsummering`) ikke feiler sporadisk.
Testen feiler da det ikke er satt opp noe kravgrunnlag tilknyttet revurderingsbehandlingen og `avsluttetDato` ikke er satt på førstegangsbehandlingen. 
Feilen oppstod sporadisk pga hvordan vi henter ut "aktiv" behandling fra `behandlinger` lista på entiteten `Vedtaksbrevgrunnlag`. Den var basert på behandlingenes `avsluttetDato`, hvor behandlingen med høyeste `avsluttetDato` eller behandlingen med `avsluttetDato` satt til null ble valgt. Her var `avsluttetDato` satt til null for både førstegangsbehandling og …
=> Fikser sporadisk feilende test

.github/dependabot.yml
Ser at vi har en del sårbarheter med høyt nivå i [nais-console](https://console.nav.cloud.nais.io/team/teamfamilie/vulnerabilities?col=SEVERITY_HIGH&dir=DESC). Dette er vanskelig å ta tak i fordi dependabot grupperer alle oppdateringer sammen, og siden én av endringene brekker noe brekker hele [PRen](https://github.com/navikt/familie-tilbake/pull/1331). 
Endrer så dependabot ikke bundler sammen alt
=> Fjern gruppering av dependabot.yml

.deploy/nais/app-dev-gcp.yaml, .deploy/nais/app-prod-gcp.yaml
Vi bruker ca 3% av cpu vi spør om. Reduserer request med 90% i prod og 95% i preprod. 
Ser også at vi bruker mer minne en vi spør om. Det kan være litt uheldig da dette kan føre til at prosessene blir drept. Det er kjipere om vi går tom for minne enn om vi "går tom for" cpu, da man alltid kan throttle en app. Øker derfor hvor mye minne vi ber om
Prod: 
Dev:
=> Reduser hvor mye CPU vi ber om

src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/domain/Kravgrunnlag431.kt
FEILUTB_0986 gjelder for manuell feilutbetaling for inntektsytelser. Vi må høre med saksbehandler fra regnskap hvorfor denne klassekoden er valgt, men godtar denne slik at tilbakekreving kan opprettes.
=> Legger til ny klassekode som har kommet fra kravgrunnlag i prod

src/main/kotlin/no/nav/familie/tilbake/behandling/BehandlingService.kt, src/main/kotlin/no/nav/familie/tilbake/config/FeatureToggleConfig.kt, src/test/kotlin/no/nav/familie/tilbake/behandling/BehandlingServiceTest.kt
Har allerede en featuretoggle i ef-sak-frontend, men lager en egen for familie-tilbake som også kan brukes senere i løypa.
=> Featuretoggle for automatisk behandling av tilbakekrevinger under 4x rettsgebyr

src/main/kotlin/no/nav/familie/tilbake/config/Constants.kt, src/main/kotlin/no/nav/familie/tilbake/vilkårsvurdering/VilkårsvurderingService.kt, src/test/kotlin/no/nav/familie/tilbake/kravgrunnlag/AutomatiskBehandlingAvKravgrunnlagUnder4RettsgebyrTest.kt
Setter samme verdier som for eksisterende automatisk behandling under halvt rettsgebyr, med unntak av begrunnelser som endres i denne PR'n.
=> Begrunnelse av vilkårsvurdering og aktsomhet settes for automatisk behandling av feilutbetalinger under 4x rettsgebyr

src/test/kotlin/no/nav/familie/tilbake/behandling/BehandlingRepositoryTest.kt, src/test/kotlin/no/nav/familie/tilbake/behandling/VarselServiceTest.kt, src/test/kotlin/no/nav/familie/tilbake/behandling/steg/StegServiceTest.kt, src/test/kotlin/no/nav/familie/tilbake/behandling/task/OppdaterFaktainfoTaskTest.kt, src/test/kotlin/no/nav/familie/tilbake/behandlingskontroll/BehandlingskontrollServiceTest.kt, src/test/kotlin/no/nav/familie/tilbake/dokumentbestilling/felles/task/DistribuerDokumentVedDødsfallTaskTest.kt, src/test/kotlin/no/nav/familie/tilbake/dokumentbestilling/felles/task/LagreBrevsporingTaskTest.kt, src/test/kotlin/no/nav/familie/tilbake/faktaomfeilutbetaling/FaktaFeilutbetalingRepositoryTest.kt, src/test/kotlin/no/nav/familie/tilbake/faktaomfeilutbetaling/FaktaFeilutbetalingServiceTest.kt, src/test/kotlin/no/nav/familie/tilbake/forvaltning/ForvaltningServiceTest.kt, src/test/kotlin/no/nav/familie/tilbake/historikkinnslag/HistorikkServiceTest.kt, src/test/kotlin/no/nav/familie/tilbake/integration/økonomi/OppdragClientTest.kt, src/test/kotlin/no/nav/familie/tilbake/iverksettvedtak/AvsluttBehandlingTaskTest.kt, src/test/kotlin/no/nav/familie/tilbake/iverksettvedtak/IverksettelseServiceTest.kt, src/test/kotlin/no/nav/familie/tilbake/iverksettvedtak/TilbakekrevingsvedtakBeregningServiceTest.kt, src/test/kotlin/no/nav/familie/tilbake/kravgrunnlag/BehandleKravgrunnlagTaskTest.kt, src/test/kotlin/no/nav/familie/tilbake/kravgrunnlag/BehandleStatusmeldingTaskTest.kt, src/test/kotlin/no/nav/familie/tilbake/kravgrunnlag/KravgrunnlagRepositoryTest.kt, src/test/kotlin/no/nav/familie/tilbake/totrinn/TotrinnServiceTest.kt, src/test/kotlin/no/nav/familie/tilbake/vilkårsvurdering/VilkårsvurderingServiceTest.kt
I forsøk på å fikse enhetstester som feiler tilfeldig i GHA
=> Endrer oppsett av integrasjonstester slik at det genereres nye ids for behandling/fagsak før det lagres til db

src/main/kotlin/no/nav/familie/tilbake/behandlingskontroll/BehandlingskontrollService.kt, src/test/kotlin/no/nav/familie/tilbake/behandlingskontroll/BehandlingskontrollServiceTest.kt
Behandlingsstegene lagres på et såpass likt tidspunkt at Sporbar sin endret tid kan være på samme millisekund.
Dette gjør at testen av og til kan finne første behandlingssteg (Fakta) selv om den skulle funnet siste (Foreldet).
Resultatet av dette blir at `fortsettBehandling` tror at siste behandlingssteg som er utført er `Fakta`, og gjør dermed neste steg til `KLAR` som er behandlingssteg `Foreldet`, i stedet for å opprette behandlingssteg `Vilkårsvurdering`.
Logg fra GHA når testen feilet. Her er Sporbar Endret tid lik for begge behandlingsstegtilstandene før fortsettBehandling utføres:
```
2024-05-03 11:04:54,321 [INFO ] [main] PdlUtil - første behandlingsstegtilstand før fortsett behandling: Behandlingsstegstilstand(id=f4e07edd-2eef-47b4-b070-3f8ecb0d97f8, …
```
=> Behandlingssteg i test lagres av og til på samme millisekund

src/main/kotlin/no/nav/familie/tilbake/api/forvaltning/ForvaltningController.kt, src/main/kotlin/no/nav/familie/tilbake/behandling/BehandlingRepository.kt, src/main/kotlin/no/nav/familie/tilbake/forvaltning/ForvaltningService.kt, src/main/kotlin/no/nav/familie/tilbake/integration/økonomi/OppdragClient.kt, src/test/kotlin/no/nav/familie/tilbake/forvaltning/ForvaltningServiceTest.kt
Endret Forvaltningsinfo-endepunktet til å også hente behandlinger som er åpne.
Splittet endepunkt til å ha eget endepunkt for henting av ikke-arkiverte kravgrunnlag.
=> Forbedret henting av forvaltningsinfo

src/main/kotlin/no/nav/familie/tilbake/api/dto/BehandlingDto.kt, src/main/kotlin/no/nav/familie/tilbake/behandling/BehandlingMapper.kt, src/main/kotlin/no/nav/familie/tilbake/oppgave/OppdaterOppgaveTask.kt, src/test/kotlin/no/nav/familie/tilbake/behandling/BehandlingServiceTest.kt
Hvis dette skjer får vi to oppgaver på samme behandling. Det er bedre å feile dersom oppgave ikke finnes, og så er det heller mulig å opprette en oppgave via forvaltningsendepunkt dersom det trengs. Vi har sett i loggene at dette ikke har skjedd i prod de siste 3 månedene.
=> Ikke lag oppgave i oppdaterOppgaveTask, da denne går i beina på LagOppgaveTask som gjøres på et senere tidspunkt

src/main/kotlin/no/nav/familie/tilbake/behandling/batch/AutomatiskSaksbehandlingService.kt, src/main/kotlin/no/nav/familie/tilbake/behandling/batch/AutomatiskSaksbehandlingTask.kt, src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/KravgrunnlagService.kt, src/test/kotlin/no/nav/familie/tilbake/kravgrunnlag/AutomatiskBehandlingAvKravgrunnlagUnder4RettsgebyrTest.kt
En behandling kan endre saksbehandlingstype fra automatisk til ordinær i enkelte tilfeller, men tilbakekrevingsvalget om automatisk behandling blir ikke endret. Saksbehandlingstype skal derfor regnes som "fasit" og feltet burde derfor brukes i alle sammenhenger hvor det er avgjørende for funksjonalitet. Dette er en utvidelse og forbedring av PR https://github.com/navikt/familie-tilbake/pull/1480 hvor det kan bli feil funksjonalitet dersom tilbakekrevingsvalg brukes fremfor saksbehandlingstype.
=> Bruk saksbehandlingstype, ikke tilbakekrevingsvalg

src/main/kotlin/no/nav/familie/tilbake/behandling/BehandlingRepository.kt, src/main/kotlin/no/nav/familie/tilbake/behandling/ValiderBehandlingService.kt, src/test/kotlin/no/nav/familie/tilbake/behandling/BehandlingServiceTest.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21849
Når vi sjekker om det er mulig å opprette en behandling på en fagsak så sjekker vi om det allerede finnes en avsluttet behandling som ikke er henlagt. Men denne tar ikke hensyn til fagsystem, og dersom eksternFagsakid er lik på tvers fagsystem, så kan ting gå galt. Tar derfor hensyn til fagsystem.
=> Ta hensyn til fagsystem ved sjekk av avsluttet behandlinger

src/main/kotlin/no/nav/familie/tilbake/api/forvaltning/ForvaltningController.kt, src/main/kotlin/no/nav/familie/tilbake/behandling/BehandlingRepository.kt, src/main/kotlin/no/nav/familie/tilbake/forvaltning/ForvaltningService.kt
Favro: [NAV-22019](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-22019)
Endepunkt som returnerer alle behandlinger hvor steget `FATTER_VEDTAK`  har status `TILBAKEFØRT`, aktivt steg kommer før `FATTER_VEDTAK` og åpen oppgave på behandlingen er av typen `GodkjenneVedtak`. Disse behandlingene er "låst" fra å bli sendt til beslutter. 
Legger her kun inn endepunkt for å finne ut hvor mange behandlinger dette gjelder for å finne ut om det er bedre å manuelt fikse de eller om vi burde skrive kode for dette. 
I nye behandlinger vil ikke lenger behandlinger kunne havne i denne tilstanden.
=> Forvalter-endepunkt for å finne alle behandlinger med åpen GodkjenneVedtak-oppgave som skulle hatt BehandleSak-oppgave

src/main/kotlin/no/nav/familie/tilbake/api/forvaltning/ForvaltningController.kt
Legger til PathVariable i Path for at endepunktet skal fungere og fjerner @Rolletilgangssjekk da det føles unødvendig for et midlertidig endepunkt som ikke returnerer noe sensitiv data.
=> Lagt til manglende PathVariable for forvalter-endepunkt

src/main/kotlin/no/nav/familie/tilbake/oppgave/FerdigstillEksisterendeOppgaverOgOpprettNyBehandleSakOppgaveTask.kt
I de tilfellene vi blir nødt til å ferdigstille en `GodkjenneVedtak`-oppgave og opprette en ny `BehandleSak`-oppgave pga nytt kravgrunnlag etter at behandling er sendt til beslutter må vi sørge for at saksbehandler på den nye `BehandleSak`-oppgaven blir satt til `behandling.ansvarligSaksbehandler`
=> Sørger for at vi setter saksbehandler til behandling.ansvarligSaksbehandler for nye BehandleSak-oppgaver

src/main/kotlin/no/nav/familie/tilbake/oppgave/FinnBehandlingerMedGodkjennVedtakOppgaveSomSkulleHattBehandleSakOppgaveTask.kt
Får bare treff på behandlinger som mangler oppgave, og ser at sjekken på om en oppgave er av typen GodkjenneVedtak aldri vil kunne bli true fordi vi forsøker å sammenligne Oppgavetype-enumen sin value mot Oppgavetype-enumens name. "GodkjenneVedtak" vil aldri kunne bli lik "GOD_VED".
=> Må sammenligne Oppgave.oppgavetype med Oppgavetype.GodkjenneVedtak.value

src/main/kotlin/no/nav/familie/tilbake/oppgave/FerdigstillEksisterendeOppgaverOgOpprettNyBehandleSakOppgaveTask.kt
Tasken `ferdigstillEksisterendeOppgaverOgOpprettNyBehandleSakTask` feiler fordi vi prøver å utlede Oppgavetype fra hentet Oppgave sin oppgavetype når vi skal ferdigstille oppgave. Oppgavetype fra Oppgave er `GOD_VED` og det vi forventer er `GodkjenneVedtak` og da feiler det. 
Fikser ved å eksplisitt sette oppgavetype til `Oppgavetype.GodkjenneVedtak` ved ferdigstillelse da vi vet at det er den typen vi skal ferdigstille uansett.
=> Fix: Må sette oppgavetype spesifikt til GodkjenneVedtak ved ferdigstilling

.github/workflows/build.yml
Dette for å unngå at man sjekker inn kode som ikke er lintet. Det kan være litt kjedelig å få med irrelevante linterendringer i en PR for nestemann dersom dette er glemt.
=> Kjør Ktlint i PR

src/main/kotlin/no/nav/familie/tilbake/behandling/steg/Foreslåvedtakssteg.kt, src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/KravvedtakstatusService.kt, src/test/kotlin/no/nav/familie/tilbake/config/IntegrasjonerClientConfig.kt, src/test/kotlin/no/nav/familie/tilbake/kravgrunnlag/KravvedtakstatusServiceTest.kt
Favro: [NAV-21928](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21928)
Tidligere når en behandling ble sendt til beslutter forsøkte vi å finne ut om vi skulle ferdigstille en `BehandleUnderkjentVedtak` eller en `BehandleSak` oppgave basert på om det fantes underkjente steg i behandlingen eller ikke. Dette ble ikke alltid riktig da saksbehandler kan ha en `BehandleSak` oppgave til tross for at det finnes underkjente steg i behandlingen. 
For å fikse dette sjekker vi nå hva slags oppgave (`BehandleSak` eller `BehandleUnderkjentVedtak`) som ligger åpen og ferdigstiller denne spesifikt.
I tillegg har jeg fikset en bug hvor vi forsøker å sammenligne feltet `oppgavetype` i `Oppgave` med `Oppgavetype.name`, når vi egentlig må sammenligne feltet …
=> Fix: Ferdigstill korrekt oppgavetype når behandling sendes til beslutter

README.md, src/test/kotlin/no/nav/familie/tilbake/database/TestdataInitializer.kt
Oppretter en dummy-behandling med kravgrunnlag ved oppstart av app. Hadde håpet på at det kunne bli en fast URL som kunne stått i readme, men eksternId i opprettTilbakekrevingRequest bruker ikke verdien videre, og det blir dermed generert en ny UUID. Mulig det er en bug. Tenkte å se på det i egen PR.
=> Oppretter en dummy behandling for lokal kjøring

src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/batch/HåndterGamleKravgrunnlagBatch.kt
Favro: [NAV-22118](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-22118)
Vi har 49 behandlinger i `ks-sak`, som kommer til å gi feilutbetalinger og dermed kravgrunnlag. Disse kravgrunnlagene ønsker vi at det skal opprettes tilbakekrevingsbehandlinger for så fort som mulig. Endrer derfor ventetiden fra 8 uker til 1 dag. Feilutbetalingene kommer fra automatiske revurderinger hvor tilbakekreving egentlig ikke skal forekomme, og `ks-sak` oppretter derfor heller ikke tilbakekrevingsbehandlingene selv.
Med en gang vi har fått opprettet de 49 behandlingene vil vi skru ventetiden tilbake til 8 uker.
=> Skrudd ned ventetid for når vi oppretter ny behandling basert på mottatt kravgrunnlag for kontantstøtte

src/main/kotlin/no/nav/familie/tilbake/behandling/consumer/HentFagsystemsbehandlingResponsConsumer.kt
https://nav-it.slack.com/archives/CJN0STWB0/p1724661202417699
Får feil med prosessering av melding, siden man ikke finner requestId med denne fagsystem.  Som da det blir kastet exception på.
Vi velger å skippe akkurat denne meldingen for å få lest resten av meldingene
=> Skipper å lese melding med id 19527f36-bc9b-494a-b8f1-f54c3dc5e968

src/main/kotlin/no/nav/familie/tilbake/behandling/consumer/HentFagsystemsbehandlingResponsConsumer.kt
Reverts navikt/familie-tilbake#1542
Kafkamelding skippet.  Trenger derfor ikke den koden lenger
=> Revert "Skipper å lese melding med id 19527f36-bc9b-494a-b8f1-f54c3dc5e968"

src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/batch/HåndterGamleKravgrunnlagBatch.kt
Justerer ventetiden tilbake til 8 uker for kontantstøtte nå som vi har fått opprettet tilbakekrevingsbehandlinger for alle fagsakene vi fikk feilutbetaling på i forbindelse med lovendring.
=> Justerer ventetid for kontantstøtte fra 1 dag til 56 dager (8 uker).

.github/workflows/build-and-deploy-dev.yml, .github/workflows/build-and-deploy-prod.yml, .github/workflows/build.yml, .github/workflows/run-e2e.yml
NAV-22116
Anbefalt å sjekke på måten
github.event.pull_request.user.login != 'dependabot[bot]'
Pluss litt opprydding
- ** endrer build-pr jobb til å bruke github.event.pull_request.user.login != 'dependabot[bot]'**
- **Fjerner unødvendig dependabot-sjekker i jobb som kun trigges av workflow_dispatch**
- **Fjerner unødvendige sjekker i andre jobber også**
=> Tar i bruk github.event.pull_request.user.login ved sjekk av om bygg er dependabot

src/main/kotlin/no/nav/familie/tilbake/behandling/steg/Foreslåvedtakssteg.kt, src/main/kotlin/no/nav/familie/tilbake/config/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/tilbake/totrinn/TotrinnService.kt, src/test/kotlin/no/nav/familie/tilbake/totrinn/TotrinnServiceTest.kt, src/test/kotlin/no/nav/familie/tilbake/totrinn/TotrinnServiceUnitTest.kt
Nytt vedtak som tidligere er underkjent skal sendes tilbake til samme beslutter. Dette er gjort i EF Sak. Nå ønsker man også dette i feilutbetalingsløsningen.
Ref slack: https://nav-it.slack.com/archives/GSWTAT0PP/p1727356409730059?thread_ts=1727355600.727169&cid=GSWTAT0PP
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-20719
=> Nytt vedtak som tidligere er underkjent skal sendes til samme beslutter 

src/main/resources/application-dev.yaml
Kan være forvirrende ved testing at prod og dev oppfører seg ulikt.
=> Sett lik regel for når foreldelse-steget skal autoutføres i dev som i prod

pom.xml, src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/felles/pdf/JournalføringService.kt, src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/manuell/brevmottaker/ManuellBrevmottakerService.kt, src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/manuell/brevmottaker/domene/ManuellBrevmottaker.kt, src/test/kotlin/no/nav/familie/tilbake/dokumentbestilling/manuell/brevmottaker/ManuellBrevmottakerServiceTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23072
Frontend-pr: https://github.com/navikt/familie-tilbake-frontend/pull/1974
Relatert til denne PRen i kontrakter: https://github.com/navikt/familie-kontrakter/pull/959
På adresser i utlandet ønsker vi ikke å sende med postnummer og poststed, siden Dokdist ikke tar hensyn til disse feltene. All informasjon skal da legges i adresselinjene. Fikser dermed validering og historikkinnslag som også godtar tomme postnummr og poststed.
Jeg setter ikke disse feltene til nullable fordi vi da også må gjøre en jobb med databasen. Og i de fleste tilfellene ønsker vi jo at postnummer og poststed skal inkluderes. Har forankret dette med @bragejahren.
=> Postnummer og poststed skal kunne være tomme

src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/vedtak/AvsnittUtil.kt, src/main/resources/templates/nb/vedtak/periode_særlige_grunner_sammenslått.hbs
Summerer feilutbetaltBeløp og bruker den verdien til å sette feilutbetaltBeløp. Dette er fordi 'reduksjon' i 'periode_særlige_grunner_feilaktig_mangelfull.hbs' blir utledet med den verdien, og den blir alltid feil når det er sammenslått. Feil tekst blir derfor vist frem i på `Vedtak`
Koden for å utlede reduksjon: `reduksjon=(neq kravgrunnlag.feilutbetaltBeløp resultat.tilbakekrevesBeløp)`
Feil tekst blir vist: 
Korrekt tekst:
=> FIX: Vise korrekt tekst på vedtak for særlige grunner

src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/vedtak/PeriodeService.kt, src/test/kotlin/no/nav/familie/tilbake/behandling/batch/AutomatiskSaksbehandlingBatchTest.kt, src/test/kotlin/no/nav/familie/tilbake/behandling/batch/AutomatiskSaksbehandlingTaskTest.kt, src/test/kotlin/no/nav/familie/tilbake/data/Testdata.kt, src/test/kotlin/no/nav/familie/tilbake/dokumentbestilling/vedtak/PeriodeServiceTest.kt
Det er ingen perioder å sammenslå dersom det bare er en periode i behandling. 
Det går an at det finnes flere perioder i vilkårsvurderingen, men bare en i fakta, så det må sjekkes at det bare er en periode i alle steg. 
Dette må settes for at målingen [her](https://metabase.ansatt.nav.no/question/4542-skal-sammensla-perioder) skal bli riktig.
I teorien må det patches for at målingen skal bli helt riktig, men det går kanskje greit å endre spørringen til å gjelde fra når denne endringen ble merget?
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-22736)
=> Skal perioder sammenslås verdi settes til ikke_aktuell dersom det bare finnes en periode

src/main/kotlin/no/nav/familie/tilbake/api/forvaltning/ForvaltningController.kt
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-22706)
I enkelte tilfeller ønsker vi å kunne ferdigstille oppgaver som ikke har blitt snappet opp riktig av systemet. I tilfelle over har vi fått feil i respons når vi har prøvd å ferdigstille en oppgave og har dermed endt opp med for mange åpne oppgaver på behandlingen.
=> Endepunkt for å ferdigstille oppgaver

src/main/kotlin/no/nav/familie/tilbake/behandling/steg/Fattevedtakssteg.kt, src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/DokumentbehandlingService.kt, src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/manuell/brevmottaker/BrevmottakerAdresseValidering.kt, src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/manuell/brevmottaker/domene/ManuellBrevmottaker.kt, src/test/kotlin/no/nav/familie/tilbake/behandling/steg/FattevedtaksstegEnhetstest.kt, src/test/kotlin/no/nav/familie/tilbake/dokumentbestilling/DokumentBehandlingServiceTest.kt, src/test/kotlin/no/nav/familie/tilbake/dokumentbestilling/DokumentbehandlingServiceEnhetstest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23182
Brevmottakere skal valideres når brev sendes ut og når beslutter godkjenner et vedtak. Hvis brevmottakerne er ugyldige (postnummer og poststed til stede for utenlandske mottakere), skal kallene feile. Beslutter skal få lov til å sende vedtaket tilbake til saksbehandler hvis dette er tilfelle. :)
=> Validering av brevmottakere

src/main/kotlin/no/nav/familie/tilbake/iverksettvedtak/IverksettelseService.kt, src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/domain/Kravgrunnlag431.kt, src/test/kotlin/no/nav/familie/tilbake/kravgrunnlag/domain/KlassekodeTest.kt
Ved iverksettelse ble `Klassekode.name` brukt for feltet `kodeKlasse`. Dette har fungert helt frem til vi nå har introdusert klassekoden `BAUTV-OP` og enum-verdien `BAUTV_OP`. Fordi vi bruker `name` så er det `BATUV_OP` som vi forsøker å sende ved iverksettelse, men denne koden er ikke gyldig, da vi skulle ha brukt `BAUTV-OP` med bindestrek (-).
Legger her til extension-function for å sette feltet `kodeKlasse`, slik at vi bruker enum-feltet `overstyrtKlassekode` dersom det finnes og ellers bare `Klassekode.name` slik som før.
=> Sørger for at vi bruker korrekt klassekode for utvidet ved iverksettelse

src/main/kotlin/no/nav/familie/tilbake/oppgave/OppdaterAnsvarligSaksbehandlerTask.kt, src/main/kotlin/no/nav/familie/tilbake/oppgave/OppdaterOppgaveTask.kt, src/test/kotlin/no/nav/familie/tilbake/oppgave/OppdaterAnsvarligSaksbehandlerTaskTest.kt
Erstattet if-statement med en try-catch slik at oppgaven oppdateres uten feil selv om enhet på oppgaven og enhet på den nye saksbehandleren ikke samsvarer.
=> Nav 23517 validere saksbehandler opp mot enhet

src/main/kotlin/no/nav/familie/tilbake/common/exceptionhandler/ApiExceptionHandler.kt, src/main/kotlin/no/nav/familie/tilbake/common/exceptionhandler/Feil.kt
I det siste har man begynt å få alarmer på ERRORs i securelogger for familie-tilbake. Skrur ned nivå i ApiExceptionHandler til WARN for feil av typen Feil. Disse logges til vanlig logg som INFO
Slettet også forvirrende exception ManglerTilgang, som kun er i bruk i ApiExceptionHandler
=> Skrur ned loggnivå på ting som logges til INFO i vanlig logg, siden man har begynt å få alarm på ERROR i securelogs

src/main/kotlin/no/nav/familie/tilbake/iverksettvedtak/task/AvsluttBehandlingTask.kt, src/test/kotlin/no/nav/familie/tilbake/iverksettvedtak/AvsluttBehandlingTaskTest.kt
Får feil i [denne](https://familie-prosessering.intern.nav.no/service/familie-tilbake/task/2300661) tasken som prøver å avslutte en behandling som allerede er avsluttet. Legger til en sjekk slik at vi ikke prøver å avslutte behandlinger som allerede er avsluttet.
=> ikke prøv å avslutte behandling som allerede er avsluttet

src/main/kotlin/no/nav/familie/tilbake/oppgave/OppgaveService.kt, src/test/kotlin/no/nav/familie/tilbake/oppgave/OppgaveServiceTest.kt
Kun sjekk på oppgaver fra familie-tilbake når vi sjekker om det er flere oppgaver i ferdigstillOppgaveTask
Vi har tasker som feiler i familie-prosessering fordi vi har flere oppgaver åpne samtidig. Trenger kun å filtrere når oppgaven er en av BehandleSak, GodkjenneVedtak eller BehandleUnderkjentVedtak. 
Task som feiler: https://familie-prosessering.intern.nav.no/service/familie-tilbake/task/2381379
Legger til filtrering på dette
=> filtrer oppgavetyper ved sjekk på flere oppgaver

src/main/kotlin/no/nav/familie/tilbake/sikkerhet/TilgangAdvice.kt
Alle automatiserte tasker som ikke trigges av saksbehandlere har saksbehandler VL, og nå som denne ble feilet så feiler alle disse hos oss. Så trenger å rulle tilbake denne endringen.
Hvis dere har lyst til å løse dette på en annen måte, så kan vi sikkert komme frem til en annen løsning, men da trenger vi tid til å implementere det først.
=> Reverterer sletting av sjekken av system tilgang

pom.xml
Vi fikk tidligere det som et transitivt dependency fra familie-felles log
=> Legg til dependency til logstash-logback-encoder

src/main/kotlin/no/nav/familie/tilbake/behandling/BehandlingService.kt, src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/felles/task/LagreBrevsporingTask.kt, src/main/kotlin/no/nav/familie/tilbake/dokumentbestilling/vedtak/SendVedtaksbrevTask.kt, src/main/kotlin/no/nav/familie/tilbake/iverksettvedtak/task/AvsluttBehandlingTask.kt, src/test/kotlin/no/nav/familie/tilbake/dokumentbestilling/felles/task/LagreBrevsporingTaskTest.kt
Den bruker bare database og kan like så greit kjøre i en transaksjon
=> Slutt å bruk task som avslutter behandling

src/main/kotlin/no/nav/familie/tilbake/config/HttpClientConfig.kt
Det blir f.eks. brukt i kall for å sjekke adressebeskyttelse. Dette krever en systembruker.
=> Benytt systembruker når vi kaller PDL direkte

kontrakter-intern/src/main/kotlin/no/nav/tilbakekreving/kontrakter/periode/Månedsperiode.kt, src/test/kotlin/no/nav/familie/tilbake/behandling/batch/AutomatiskSaksbehandlingBatchTest.kt, src/test/kotlin/no/nav/familie/tilbake/behandling/batch/AutomatiskSaksbehandlingTaskTest.kt, src/test/kotlin/no/nav/familie/tilbake/behandling/steg/StegServiceTest.kt, src/test/kotlin/no/nav/familie/tilbake/beregning/TilbakekrevingsberegningServiceTest.kt, src/test/kotlin/no/nav/familie/tilbake/data/Testdata.kt, src/test/kotlin/no/nav/familie/tilbake/dokumentbestilling/vedtak/PeriodeServiceTest.kt, src/test/kotlin/no/nav/familie/tilbake/dokumentbestilling/vedtak/VedtaksbrevServiceTest.kt, src/test/kotlin/no/nav/familie/tilbake/foreldelse/ForeldelseServiceTest.kt, src/test/kotlin/no/nav/familie/tilbake/kravgrunnlag/KravgrunnlagServiceTest.kt, src/test/kotlin/no/nav/familie/tilbake/oppgave/OppgavePrioritetServiceTest.kt, src/test/kotlin/no/nav/familie/tilbake/vilkårsvurdering/VilkårsvurderingServiceTest.kt, src/test/kotlin/no/nav/tilbakekreving/Dato.kt, src/test/kotlin/no/nav/tilbakekreving/kravgrunnlag/KravgrunnlagValidatorTest.kt, src/test/kotlin/no/nav/tilbakekreving/kravgrunnlag/MånedsperiodeValidatorTest.kt
Tidligere har tester i VedtaksbrevServiceTest hatt ulike datoer for vurdering og kravgrunnlag. Det gir lite mening og fører til vedtaksbrev som ikke matcher reelle tillfeller
=> Fikser opp i tester så datoer henger sammen med vurderinger

modell/src/main/kotlin/no/nav/tilbakekreving/beregning/Beregning.kt, modell/src/main/kotlin/no/nav/tilbakekreving/beregning/delperiode/Foreldet.kt, modell/src/test/kotlin/no/nav/tilbakekreving/beregning/BeregningTest.kt, modell/src/test/kotlin/no/nav/tilbakekreving/beregning/delperiode/DelperiodeTest.kt
Før fikk hver kravgrunnlagsperiode ulik dato for vurdert foreldelse. Dette gjorde at vi ikke klarte å slå sammen igjen periodenene for oppsummeringen. Denne endringen fører til at vedtaksoppsummering i vedtaksløsning og vedtaksbrev vises som en sammenhengende periode
=> Unngå unødvendig splitting av perioder med vurdert foreldelse

modell/src/main/kotlin/no/nav/tilbakekreving/beregning/Beregning.kt, modell/src/main/kotlin/no/nav/tilbakekreving/beregning/delperiode/Vilkårsvurdert.kt, modell/src/test/kotlin/no/nav/tilbakekreving/beregning/BeregningTest.kt
Dersom en periode har flere klassekoder og manuelt satt beløp vil hvert beløp i perioden få satt beløpet. Dersom det er to beløp vil derfor beløpet dobbles.
=> Legger til guard clause så vi ikke iverksetter vedtak med feil beløp

src/main/kotlin/no/nav/familie/tilbake/oppgave/OppgaveService.kt
Gjør så vi kan få opprettet en oppgave for en enkeltsak som er i en ødelagt tilstand. Saksbehandler som skal tilordnes oppgaven har ikke tilgang til enheten vi prøver å opprette oppgaven på, så vi oppretter en oppgave uten tilordnet saksbehandler, så kan vi i ettertid bytte enhet.
=> Manuell workaround for å opprette oppgave uten tilordnet saksbehandler

src/main/kotlin/no/nav/familie/tilbake/api/BeregningController.kt, src/main/kotlin/no/nav/familie/tilbake/beregning/GammelVilkårsvurderingAdapter.kt, src/main/kotlin/no/nav/familie/tilbake/beregning/TilbakekrevingsberegningService.kt, src/main/kotlin/no/nav/familie/tilbake/beregning/VilkårsvurderingsperiodeAdapter.kt, src/test/kotlin/no/nav/familie/tilbake/beregning/TilbakekrevingsberegningVilkårTest.kt
Sender logContext videre til VilkårsvurderingsperiodeAdapter for å sende riktig feilmelding til frontend.
=> Feilmelding ved uferdige periodevurderinger
